package com.centris.campus.util;

public class ClassFeeSetupDetails {
	
	/*public static final String GET_CLASS_DETAILS ="select distinct a.acadamic_id,a.acadamic_year,cd.classdetail_id_int,cd.classdetails_name_var,t.termid,t.termname from campus_acadamicyear a,campus_classdetail cd,campus_fee_termdetails t where a.acadamic_id=? and isTransportTerm = 'N' group by a.acadamic_id,cd.classdetail_id_int,t.termid order by length(a.acadamic_id),length(cd.classdetail_id_int),length(t.termid),a.acadamic_id,cd.classdetail_id_int,t.termid";
	public static final String GET_FEE_COUNT="select count(fsd.feecode) as feecount from campus_fee_setup fs,campus_fee_setupdetails fsd where fs.feeSettingcode = fsd.feeSettingCode and fs.ClassCode=? and fs.AccyearCode=? and fs.Termcode=?";
	*//*public static final String SERCH_FEE_DETAILS="select distinct a.acadamic_id,a.acadamic_year,cd.classdetail_id_int,cd.classdetails_name_var,t.termid,t.termname from campus_acadamicyear a,campus_classdetail cd,campus_fee_termdetails t where (a.acadamic_year like ? or cd.classdetails_name_var like ? or t.termname like ?) and a.acadamic_id=? group by a.acadamic_id,cd.classdetail_id_int,t.termid order by length(a.acadamic_id),length(cd.classdetail_id_int),length(t.termid),a.acadamic_id,cd.classdetail_id_int,t.termid";*/
	public static final String GET_APPROVED_FEES = "select distinct fm.FeeCode,fm.FeeName,fsd.feeSettingCode,fsd.feeAmount from campus_fee_setupdetails fsd,campus_fee_setup fs,campus_fee_master fm where fsd.feeSettingCode=fs.feeSettingcode and fsd.feecode=fm.FeeCode and fs.ClassCode=? and fs.AccyearCode=? and fs.Termcode=? and fs.specialization=?";
	public static final String GET_ALL_FEES = "select distinct fm.FeeCode,fm.FeeName from campus_fee_master fm where fm.FeeCode  not in(select fsdd.FeeCode from campus_fee_setupdetails fsdd, campus_fee_setup fss1 where  fss1.feeSettingcode=fsdd.feeSettingCode  and  fss1.ClassCode=? and fss1.AccyearCode=? and fss1.Termcode=? and fss1.specialization=?)";
	public static final String INSERT_APPROVED_FEES_IN_FEE_SETUP = "insert into campus_fee_setup(feeSettingcode,ClassCode,AccyearCode,locationId,Termcode,specialization,createdby,createtime)values(?,?,?,?,?,?,?,now())";
	public static final String INSERT_APPROVED_FEES = "insert into  campus_fee_setupdetails(feeSettingCode,feecode,feeAmount)values(?,?,?);";
	public static final String DELETE_FEE_CODE = "delete from campus_fee_setupdetails where feeSettingCode=? and feecode=?";
	public static final String UPDATE_FEE_AMOUNT = "update campus_fee_setupdetails set feeAmount=? where feeSettingCode in (select feeSettingcode from campus_fee_setup where ClassCode=? and AccyearCode=? and Termcode=? and specialization=?) and feecode=?";
	public static final String DELETE_FEE_AMOUNT = "DELETE FROM campus_fee_setupdetails where feeSettingCode in (select feeSettingcode from campus_fee_setup where ClassCode=? and AccyearCode=? and Termcode=? and specialization=?) and feecode=?";
	public static final String FEE_SETUP_COUNT ="select count(*),feeSettingcode from campus_fee_setup where ClassCode=? and AccyearCode=? and Termcode=? and specialization=? and locationId=?"; 
	public static final String INSERT_APPROVED_FEES_AMT="insert into  campus_fee_setupdetails(feeSettingCode,feecode,feeAmount)values((select feeSettingcode from campus_fee_setup where ClassCode=? and AccyearCode=? and Termcode=? and specialization=? ),?,?)";
	public static final String GET_CLASS_DETAILS ="SELECT cl.Location_Name,cd.locationId, a.acadamic_id,a.acadamic_year,cd.classdetail_id_int,cd.classdetails_name_var ,SUBSTR(cd.classdetail_id_int,4) id FROM campus_acadamicyear a,campus_classdetail cd,campus_location cl WHERE cd.locationId=cl.Location_Id AND a.acadamic_id=? AND cd.locationId Like ? ORDER BY CAST(id AS UNSIGNED)";
	public static final String GET_FEE_COUNT="select count(fsd.feecode) as feecount from campus_fee_setup fs,campus_fee_setupdetails fsd where fs.feeSettingcode = fsd.feeSettingCode and fs.ClassCode=? and fs.AccyearCode=? and fs.locationId=?";
	public static final String SERCH_FEE_DETAILS="SELECT DISTINCT a.acadamic_id,a.acadamic_year,cd.classdetail_id_int,cd.classdetails_name_var,t.termid,t.termname,CASE WHEN cd.classdetail_id_int=ccs.ClassDetails_Id THEN ccs.Specialization_Id ELSE '-' END Specialization_Id,CASE WHEN cd.classdetail_id_int=ccs.ClassDetails_Id THEN ccs.Specialization_name ELSE '-' END Specialization_name FROM campus_acadamicyear a,campus_classdetail cd,campus_fee_termdetails t ,campus_class_specialization ccs where (a.acadamic_year like ? or cd.classdetails_name_var like ? or t.termname like ?) AND a.acadamic_id=? group by a.acadamic_id,cd.classdetail_id_int,t.termid,ccs.Specialization_Id order by a.acadamic_id,cd.classdetail_id_int,t.termid";
	public static final String GET_TERM = "SELECT DISTINCT termid ,termname FROM campus_fee_termdetails WHERE accyear=? AND locationId=? ORDER BY CAST(SUBSTR(termid,4) AS UNSIGNED)";
	public static final String GET_ALL_FEE = "SELECT DISTINCT FeeCode,FeeName FROM campus_fee_master where locationId=? and academicYear=? ";
	public static final String GET_FEE_HEADING = "SELECT (SELECT classdetails_name_var  FROM campus_classdetail WHERE classdetail_id_int=? and locationId=?) AS className ,(SELECT acadamic_year  FROM campus_acadamicyear WHERE acadamic_id=?) AS year,(SELECT COUNT(Specialization_Id)  FROM campus_class_specialization WHERE ClassDetails_Id=? and locationId=?) AS SpecializationCount";
	public static final String CHECK_FEE_SETUP = "SELECT COUNT(feeSettingcode),feeSettingcode FROM campus_fee_setup WHERE ClassCode=? AND AccyearCode=? AND Termcode=? AND locationId=?";
	public static final String GET_ALL_FEE_AMOUNT = "SELECT feeAmount  FROM campus_fee_setupdetails WHERE feeSettingCode=? AND feecode=?";
	public static final String GET_SPECIALIZATION = "SELECT Specialization_Id,Specialization_name FROM campus_class_specialization WHERE ClassDetails_Id=? AND locationId=? ORDER BY Specialization_name";
	public static final String CHECK_FEE_SETUP_SPECIALIZATION = "SELECT COUNT(feeSettingcode),feeSettingcode FROM campus_fee_setup WHERE ClassCode=? AND AccyearCode=? AND Termcode=? AND specialization=? AND locationId=?";
}
