package com.centris.campus.util;

public class EventsSqlUtils {
	//Events setting
	public static  String SaveEventRegistration ="INSERT INTO `campus_event_registration` (`event_Id`,`eventName`,`eventType`,`startsOn`,`endsOn`,`startRegistation`,`endRegstation`,`regStatus`,`description`,`isHouseWise`,`isAprvPartReg`,`accyer_ID`,`location_ID`)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)";
	public static String getEventRegistrationList="	SELECT CASE WHEN CURDATE()<e.`endRegstation` THEN 'OPEN'  ELSE 'CLOSED' END regStatus,e.event_Id,e.`accyer_ID`,e.`location_ID`,l.Location_Name,a.acadamic_year,e.eventName,e.startsOn,e.endsOn FROM `campus_event_registration` e LEFT JOIN `campus_acadamicyear` a ON a.`acadamic_id`=e.`accyer_ID` LEFT JOIN campus_location l ON l.Location_Id=e.location_ID WHERE e.accyer_ID LIKE ? AND e.location_ID LIKE ? AND (l.Location_Name LIKE ? OR a.acadamic_year LIKE ? OR e.eventName LIKE ? OR e.startsOn LIKE ? OR e.endsOn LIKE ? OR e.regStatus LIKE ?)";
	public static String updateEventRegistarion ="UPDATE campus_event_registration SET eventType=?,startsOn=?,endsOn=?,startRegistation=?,endRegstation=?, regStatus=?,description=?,isHouseWise=?,isAprvPartReg=?,eventName=? WHERE event_Id=?";
	public static String deleteEventRegistration="DELETE  FROM `campus_event_registration` WHERE `event_Id`=?";
	public static String getDataForUpdate ="SELECT `event_Id`,`eventName`,`eventType`,`startsOn`,`endsOn`,`startRegistation`,`endRegstation`,`regStatus`,`description`,`isHouseWise`,`isAprvPartReg`,location_ID FROM `campus_event_registration` WHERE `event_Id`=?";

	//Category setting
	public static String getclassList ="SELECT DISTINCT c.`classdetail_id_int`,c.`classdetails_name_var` FROM `campus_event_registration` e LEFT JOIN `campus_classdetail` c ON c.`locationId`=e.`location_ID`";
	public static String getEventName ="SELECT `event_Id`,`eventName` FROM `campus_event_registration`";
	public static String saveCategory ="INSERT INTO `campus_event_category`(`categoryId`,`categoryName`,`eventId`,`classList`)VALUES(?,?,?,?)";
	public static String getCategoryName ="SELECT `categoryId`,`categoryName` FROM `campus_event_category` WHERE `eventId`=?";
	public static String getCategorySettingList ="SELECT e.`event_Id`,e.`eventName`,c.`categoryName`,c.`categoryId`,c.`classList` FROM `campus_event_category` c LEFT JOIN `campus_event_registration` e ON e.`event_Id`=c.`eventId` WHERE `eventId` LIKE ? AND `categoryId` LIKE ? order by categoryName asc" ;
	public static String deleteCategory ="DELETE FROM `campus_event_category` WHERE categoryId =?";
	public static String getDataForUpdateCategory="SELECT c.event_Id,e.`categoryId`,c.`eventName`,e.`categoryName`,e.`classList` FROM `campus_event_category` e LEFT JOIN `campus_event_registration` c ON c.`event_Id`= e.`eventId` WHERE e.`categoryId`=?";
	public static String updateCategory ="UPDATE `campus_event_category` SET `categoryName`=?,`classList`=? WHERE `categoryId`=?";

	//stage Setting
	public static String stageSetting="INSERT INTO `campus_event_stage`(stageId,`eventId`,`stageName`,`building`,`floorName`,`roomNumber`,`description`) VALUES(?,?,?,?,?,?,?)";
	public static String getstageList="SELECT `stageId`,`stageName` FROM `campus_event_stage` WHERE `eventId`=?";
	public static String getStageSettingList="SELECT s.`stageId`,e.`eventName`,s.`eventId`,s.`stageName`,s.`building`,s.`floorName`,s.`roomNumber` FROM `campus_event_stage` s LEFT JOIN `campus_event_registration` e ON e.`event_Id`=s.eventId WHERE `eventId` LIKE ? AND `stageId` LIKE ? order by s.`stageName` asc";
	public static String deleteStage="DELETE  FROM `campus_event_stage` WHERE `stageId` =?";
	public static String getDataForUpdateStage="SELECT e.`eventName`,s.`eventId`,s.stageId,s.`stageName`,s.`building`,s.`floorName`,s.`roomNumber`,s.`description` FROM `campus_event_stage` s LEFT JOIN campus_event_registration e ON e.`event_Id` = s.`eventId` WHERE s.`stageId`=?";
	public static String updateStageSetting="UPDATE `campus_event_stage` SET `stageName`=?,`building`=?,`description`=?,`floorName`=?,`roomNumber`=? WHERE `stageId`=?";

	public static String criteriaSetting="INSERT INTO `campus_event_criteria`(Criteria_Id,Event,`Programme_Name`,`Category`,`Criteria`,Max_marks) VALUES(?,?,?,?,?,?)";
	public static String getCriteriaSettingList="SELECT ecri.Criteria_Id,evt.`event_Id`,evt.eventName,ecat.`categoryId`,ecat.categoryName,epro.`program_id`,epro.program_name,ecri.Criteria,ecri.Max_marks  FROM campus_event_registration evt JOIN campus_event_criteria ecri ON evt.event_Id = ecri.`Event` JOIN campus_event_category ecat ON ecat.categoryId = ecri.Category JOIN campus_event_programcreation epro ON epro.program_id = ecri.Programme_Name WHERE ecri.`Event` LIKE ?  AND ecri.Category LIKE ? AND ecri.Programme_Name LIKE ? ORDER BY evt.eventName,ecat.categoryName,epro.program_name";
	public static String getCategory="SELECT `categoryId`,`categoryName` FROM `campus_event_category` ";
	public static String deleteCriteria="DELETE  FROM `campus_event_criteria` WHERE `Criteria_Id` =?";
	public static String getDataForUpdateCriteria="select * from campus_event_criteria where Criteria_Id=?";
	public static String updateCriteriaSetting="UPDATE `campus_event_criteria` SET `Event`=?,`Programme_Name`=?,`Category`=?,`Criteria`=?,`Max_marks`=?  WHERE `Criteria_Id`=?";
	public static String getProgramName ="SELECT `program_id`,`program_name` FROM `campus_event_programcreation`";
	public static String getCategoryList="SELECT `Category` FROM `campus_event_criteria` WHERE `Event_id`=?";
	public static String getProgrammeName="SELECT `program_id`,`program_name` FROM `campus_event_programcreation` WHERE `category_id`=? and event_id=?";

 
	//GreenRoom Setting
	public static String saveGreenRoom ="INSERT INTO `campus_event_greenroom`(`greenroom_id`,`event_id`,`greenroom_name`,`greenroom_type`,`building`,`floor`,`roomno`) VALUES(?,?,?,?,?,?,?)";
	public static String getGreenRoom="SELECT `greenroom_name`,`greenroom_id` FROM `campus_event_greenroom` WHERE `event_id`=?";
	public static String getGreenRoomList ="SELECT g.`greenroom_id`,e.`eventName`,g.`greenroom_name`,g.`greenroom_type`,g.`building`,g.`floor`,g.`roomno` FROM `campus_event_greenroom` g LEFT JOIN `campus_event_registration` e ON e.`event_Id` = g.`event_id` WHERE g.`event_id` LIKE ? AND g.`greenroom_id` LIKE ?";
	public static String deleteGreenRoom="DELETE FROM `campus_event_greenroom` WHERE `greenroom_id`=?";
	public static String getDataForUpdateGreenRoom="SELECT g.`greenroom_id`,g.event_id,e.`eventName`,g.`greenroom_name`,g.`greenroom_type`,g.`building`,g.`floor`,g.`roomno` FROM `campus_event_greenroom` g LEFT JOIN `campus_event_registration` e ON e.`event_Id` = g.`event_id` WHERE g.`greenroom_id`= ?";
	public static String updateGreenRoom ="UPDATE `campus_event_greenroom`  SET `greenroom_name`=?,`greenroom_type`=?,`building`=?,`floor`=?,`roomno`=? WHERE `greenroom_id`=?"; 

	//program Creation
	public static String saveProgram ="INSERT INTO `campus_event_programcreation`(`program_id`,`event_id`,`category_id`,`program_name`,noOfJudge,`programType`,`participantsType`,`teamsAllowed`,`noOfparticipants`,`duration`,`isHouseWise`,`noOfHouseChildren`,`programDate`,`info_staff`,`info_general`)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
	public static String getprogramName="SELECT `program_name`,`program_id`,`isHouseWise` FROM `campus_event_programcreation` WHERE `event_id`like ? AND category_id like ?";
	public static String getProgramSettingList="SELECT r.`eventName`,p.`program_name`,c.`categoryName`,p.`isHouseWise`,CASE WHEN p.`isHouseWise`='yes' THEN p.noOfHouseChildren ELSE '-' END noOfHouseChildren,p.`program_id`,p.`programType`,p.`participantsType`,CASE WHEN p.`teamsAllowed` !='' THEN p.teamsAllowed ELSE '-' END teamsAllowed,p.`noOfparticipants`,p.`duration`,p.`programDate` FROM `campus_event_programcreation` p LEFT JOIN `campus_event_registration` r ON r.`event_Id`=p.event_id LEFT JOIN `campus_event_category` c ON c.`categoryId` =p.`category_id`  WHERE p. `program_id` LIKE ? AND r.`event_Id` LIKE ? AND c.`categoryId` LIKE ? ORDER BY programType ASC ";
	public static String deleteProgram="DELETE FROM `campus_event_programcreation` WHERE `program_id`=?";
	public static String getDataforUpdateProgram="SELECT noOfJudge,`program_id`,`event_id`,`category_id`,`program_name`,`programType`,`participantsType`,`teamsAllowed`,`noOfparticipants`,`duration`,`isHouseWise`,`noOfHouseChildren`,`programDate`,`info_staff`,`info_general` FROM `campus_event_programcreation` WHERE `program_id`=?";
	public static String updateProgram="UPDATE `campus_event_programcreation` SET `programType`=?,`participantsType`=?,`teamsAllowed`=?,`noOfparticipants`=?,`duration`=?,`isHouseWise`=?,`noOfHouseChildren`=?,`programDate`=?,`info_staff`=?,`info_general`=?,program_name=?,noOfJudge=? WHERE `program_id`=? ORDER BY `created_time` DESC";
	public static String checkDupProg ="SELECT COUNT(`program_name`),program_name FROM `campus_event_programcreation` WHERE `event_id`=? AND `category_id`=? and program_name=?";
	public static String chkdupParticipantsType="SELECT COUNT(`programType`) FROM `campus_event_programcreation` WHERE `program_name`=? AND `participantsType`=?";
	
	// event student Registration
	public static String getHouse ="SELECT `house_id`,`housename` FROM `campus_house_settings`";
	public static String saveEventStudentReg="INSERT INTO `campus_event_studentregistration`(`registration_id`,`event_id`,`category_id`,`program_id`,`house_id`,`captain_admissionNo`,participants_admissionNo,`info_staff`,`info_synopsys`,`info_req`,participateType,registrationNo,accId)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)";
	public static String getAdmissionNo="SELECT `student_admissionno_var`,CONCAT(`student_fname_var`,'',`student_lname_var`) as studentName FROM `campus_student` WHERE `student_admissionno_var` LIKE ?";
	public static String studentAdmnName="SELECT student_id_int,`student_admissionno_var`,CONCAT(`student_fname_var`,'',`student_lname_var`) as studentName FROM `campus_student`  WHERE student_admissionno_var  NOT IN (?)"; 
	public static String getHouseNameList_Group = "SELECT DISTINCT s.`house_id`,h.`housename` FROM `campus_event_studentregistration` s JOIN `campus_house_settings` h ON h.`house_id`=s.`house_id` WHERE s.`participateType`='group' AND s.`event_id` LIKE ? AND s.`category_id` LIKE ? AND s.`program_id` LIKE ?";
	public static String getHouseNameList_Indiv = "SELECT DISTINCT s.`house_id`,h.`housename` FROM `campus_event_studentregistration` s JOIN `campus_house_settings` h ON h.`house_id`=s.`house_id` WHERE s.`participateType`='individual' AND s.`event_id` LIKE ? AND s.`category_id` LIKE ? AND s.`program_id` LIKE ?";
	public static String getEventNameList_Group ="SELECT DISTINCT r.`eventName`,s.`event_id`  FROM `campus_event_studentregistration` s LEFT JOIN `campus_event_registration` r ON r.`event_Id`=s.`event_id` WHERE s.`participateType`='group'";
	public static String getEventNameList_Indiv ="SELECT DISTINCT r.`eventName`,s.`event_id`  FROM `campus_event_studentregistration` s LEFT JOIN `campus_event_registration` r ON r.`event_Id`=s.`event_id` WHERE s.`participateType`='individual'";
	public static String getRegNumberList_Indiv = "SELECT `registration_id` FROM `campus_event_studentregistration` WHERE `event_id`=? and `participateType`='individual'";
	public static String getProgNameForStdReg_Group ="SELECT DISTINCT p.`isHouseWise`,p.`program_name`,p.`program_id` FROM `campus_event_studentregistration` s LEFT JOIN `campus_event_programcreation` p  ON p.`program_id`=s.`program_id` WHERE s.`participateType`='group' AND s.`category_id` like ? and s.`event_id` like ?";
	public static String getProgNameForStdReg_Indiv ="SELECT DISTINCT  p.`isHouseWise`,p.`program_name`,p.`program_id` FROM `campus_event_studentregistration` s LEFT JOIN `campus_event_programcreation` p  ON p.`program_id`=s.`program_id` WHERE s.`participateType`='individual' AND s.`category_id` like ? and s.`event_id` like ?";
	public static String getStageNameListGroup="SELECT s.`stageName`,s.`stageId` FROM `campus_event_program_scheduling` p LEFT JOIN `campus_event_stage` s ON s.`stageId`=p.`Stage` WHERE p.`Event_name` LIKE ? AND p.`Program_name` LIKE ?";
	
	public static String GET_PARTICPANT_LIST_FROM_EVENT_REGISTRATION="SELECT ces.*, CASE WHEN  h.`housename`!='' THEN  h.`housename` ELSE  '-' END houseName FROM campus_event_studentregistration ces LEFT JOIN campus_house_settings h ON h.house_id=ces.house_id WHERE event_id LIKE ? AND `participateType`='group' and `program_id` LIKE ? AND `category_id` LIKE ? and ces.`house_id` LIKE ?";
	public static String GET_PARTICPANT_LIST_FROM_STUDENT_REGISTRATION="SELECT l.`Location_Name`,cs.*,csc.*, csc.student_rollno rollNo,csc.student_imgurl_var imgurl_var,cc.classdetails_name_var FROM campus_student cs LEFT JOIN campus_student_classdetails csc ON csc.student_id_int=cs.student_id_int LEFT JOIN campus_classdetail cc ON (cc.classdetail_id_int=csc.classdetail_id_int AND cc.locationId=csc.locationId) LEFT JOIN `campus_location` l ON l.`Location_Id`=cs.`locationId`  WHERE cs.student_admissionno_var=? AND csc.fms_acadamicyear_id_int=? ";
	public static String getEventRegiListIndividual ="SELECT DISTINCT cep.program_name,s.`participateType`,s.registrationNo,CONCAT(cs.`student_admissionno_var`,'_',cs.`student_fname_var`,' ',cs.`student_lname_var`) studentName, csc.`student_rollno`,cc.classdetails_name_var,l.`Location_Name`,csc.`student_imgurl_var`,  CASE WHEN  h.`housename`!='' THEN  h.`housename` ELSE  '-' END houseName,`registration_id`,s.`captain_admissionNo`,s.`registration_id`,s.created_time,csec.classsection_name_var FROM `campus_event_studentregistration` s LEFT JOIN `campus_student` cs ON cs.`student_admissionno_var`=s.`captain_admissionNo` LEFT JOIN campus_student_classdetails csc ON csc.student_id_int=cs.student_id_int LEFT JOIN campus_classdetail cc ON (cc.classdetail_id_int=csc.classdetail_id_int AND cc.locationId=csc.locationId) JOIN  campus_classsection csec ON csec.classsection_id_int=csc.classsection_id_int LEFT JOIN `campus_house_settings` h ON h.`house_id`=s.`house_id` LEFT JOIN `campus_location` l ON l.`Location_Id`=cs.`locationId` JOIN `campus_event_programcreation` cep ON cep.program_id=s.`program_id` WHERE s.`participateType`='individual' AND s.`event_id` like ? AND s.`category_id` LIKE ? AND s.`program_id` LIKE ? AND s.`house_id` LIKE ? and s.accId like ? AND csc.fms_acadamicyear_id_int=? ORDER BY `created_time` DESC";
	public static String getDataForUpdateEventStdRegis="SELECT CONCAT( cs.`student_admissionno_var`,'_',cs.`student_fname_var`,' ',cs.`student_lname_var`) cName, s.program_id,s.house_id,s.category_id,s.`event_id`,s.`registration_id`,s.`captain_admissionNo`,s.`participants_admissionNo`,s.`info_staff`,s.`info_synopsys`,s.`info_req`,s.participateType FROM `campus_event_studentregistration` s  JOIN campus_student cs ON cs.`student_admissionno_var` =s.captain_admissionNo WHERE `registration_id`=?";
	public static String deleteEventStudReg="DELETE FROM `campus_event_studentregistration` WHERE `registration_id`=?";
	public static String updateEventStudentReg="UPDATE `campus_event_studentregistration` SET `captain_admissionNo`=?,`participants_admissionNo`=?,`info_staff`=?,`info_synopsys`=?,`info_req`=? WHERE `registration_id`=?";
	public static String udpateIndividualSave="UPDATE `campus_event_studentregistration` SET  `house_id`=?,`captain_admissionNo`=?,`participants_admissionNo`=?,`info_staff`=?,`info_synopsys`=?,`info_req`=? WHERE `registration_id`=?";
	public static String GET_PARTICPANT_LIST_GROUP="SELECT ces.*,h.housename FROM campus_event_studentregistration ces LEFT JOIN campus_house_settings h ON h.house_id=ces.house_id WHERE event_id LIKE ? AND `category_id` like ? AND `program_id` like ? and `participateType`='group'";
	
	public static String getCriteriaList="SELECT `Criteria_Id`,`Criteria` FROM `campus_event_criteria` WHERE `Programme_Name`=? and Event_name=? and Category=?";
    public static String prizeSetting="INSERT INTO `campus_event_prizelevel`(prize_id,`event_name`,`category`,`program_name`,`seq_no`,`prize_level`,`points`,description) VALUES(?,?,?,?,?,?,?,?)";
    public static String updatePrizeSetting ="UPDATE `campus_event_prizelevel` SET `event_name`=?,`program_name`=?,`category`=?,`seq_no`=?,`prize_level`=? ,`points`=? ,description=? WHERE `prize_id`=?";
    public static String GET_PARTICPANT_LIST="SELECT ces.*,h.housename FROM campus_event_studentregistration ces LEFT JOIN campus_house_settings h ON h.house_id=ces.house_id WHERE ces.event_id=? and ces.participateType='group' and ces.program_id LIKE ? and ces.category_id=?";
    public static String GET_PARTICPANT_LIST_1="SELECT ces.*,h.housename FROM campus_event_studentregistration ces LEFT JOIN campus_house_settings h ON h.house_id=ces.house_id WHERE ces.event_id=? and ces.program_id=? and ces.category_id=? AND ces.house_id LIKE ?";
    public static String getPrizeSettingList=" SELECT prz.`prize_id`,evt.`eventName`,cat.`categoryName`,pro.`program_name`,prz.`seq_no`,prz.`prize_level`,prz.`points`,prz.`description`   FROM `campus_event_prizelevel` prz   JOIN campus_event_registration evt ON evt.event_Id=prz.event_name   JOIN campus_event_category cat ON cat.categoryId=prz.`category`  JOIN campus_event_programcreation pro ON pro.program_id=prz.program_name  WHERE prz.`event_name` LIKE ?  AND prz.`category` LIKE ?   AND prz.program_name LIKE ?  ORDER BY evt.eventName,cat.categoryName,pro.program_name";
    public static String getDataForUpdatePrize="select * from campus_event_prizelevel where prize_id=?";
	public static String deletePrize="DELETE  FROM `campus_event_prizelevel` WHERE `prize_id` =?";
	public static String getPrizeList="SELECT `prize_id`,`prize_level` FROM `campus_event_prizelevel` WHERE `program_name`=? and event_name=? and category=?";
	public static String getSeqList="SELECT `prize_id`,`seq_no` FROM `campus_event_prizelevel` WHERE prize_level=? and `program_name`=? and event_name=? and category=?  ";
	public static String getPointsList="SELECT `points` FROM `campus_event_prizelevel` WHERE  seq_no=? and prize_level=? and `program_name`=? and event_name=? and category=?";
	
	public static String getProgramList="SELECT `program_id`,`program_name` FROM `campus_event_programcreation` WHERE  event_id=?";
	public static String saveProgramscheduling="INSERT INTO `campus_event_program_scheduling`(Scheduling_id,`Event_name`,`Program_name`,`Program_date`,`Stage`,`Green_room`,`Makeup_report`,`BackStage_report`,Program_time) VALUES(?,?,?,?,?,?,?,?,?)";
	public static String updateProgramscheduling="UPDATE `campus_event_program_scheduling` SET `Event_name`=?,`Program_name`=?,`Program_date`=?,`Stage`=? ,`Makeup_report`=?,`Green_room`=? ,BackStage_report=? ,Program_time=? WHERE `Scheduling_id`=?";
	public static String getProgramscheduling="SELECT reg.eventName,reg.event_Id,pgrm.program_id,pgrm.program_name,pgrm.programDate,stg.stageId,stg.stageName,grn.greenroom_id,grn.greenroom_name FROM campus_event_registration reg    JOIN campus_event_programcreation pgrm ON pgrm.event_id=reg.event_Id   JOIN `campus_event_stage_allocation` cesa ON pgrm.program_id=cesa.ProgramId   JOIN campus_event_stage stg ON stg.stageId=cesa.StageName JOIN campus_event_greenroom grn ON grn.event_id=reg.event_Id where reg.event_Id like ? ORDER BY pgrm.programDate,reg.eventName,pgrm.program_name";
	public static String getDataForUpdateScheduling="select * from campus_event_program_scheduling where Scheduling_id=?";
	public static String deleteScheduling="DELETE  FROM `campus_event_program_scheduling` WHERE `Scheduling_id` =?";
	public static String getProgramDatescheduling="SELECT reg.eventName,reg.event_Id,pgrm.program_id,pgrm.program_name,pgrm.programDate,stg.stageId,stg.stageName,grn.greenroom_id,grn.greenroom_name FROM campus_event_registration reg    JOIN campus_event_programcreation pgrm ON pgrm.event_id=reg.event_Id   JOIN `campus_event_stage_allocation` cesa ON pgrm.program_id=cesa.ProgramId   JOIN campus_event_stage stg ON stg.stageId=cesa.StageName JOIN campus_event_greenroom grn ON grn.event_id=reg.event_Id where reg.event_Id like ? and programDate like ? ORDER BY pgrm.programDate,reg.eventName,pgrm.program_name";

	public static String getStage="SELECT stageId,stageName FROM campus_event_stage WHERE `eventId`=?";
	public static String getParticipants="select reg.captain_admissionNo,concat(cs.student_fname_var,cs.student_lname_var) as name from campus_event_studentregistration reg left join campus_student cs on cs.student_admissionno_var=reg.captain_admissionNo  where reg.event_id=? AND captain_admissionNo NOT IN (?)";
	public static String saveStageAllocation="insert into campus_event_stage_allocation(AllocationId,Event,StageName,ProgramId) values (?,?,?,?)";
	public static String getMappedParticipants="SELECT stg.`stageName`,al.`ParticipantsName`FROM campus_event_stage_allocation al JOIN `campus_event_stage` stg ON stg.`stageId`=al.`StageName` WHERE al.StageName=?";

	public static String geteventname ="SELECT `event_Id`,`eventName` FROM `campus_event_registration`";
	public static String geteventcategory ="SELECT `categoryId`,`categoryName` FROM `campus_event_category` WHERE `eventId` LIKE ? ";
	public static String getprogramname ="SELECT `program_id`,`program_name` FROM `campus_event_programcreation` WHERE `category_id` LIKE ?";

	public static String getProgramNumberingDetails="SELECT st.registration_id,prog.program_name,st.category_id,CONCAT(student_fname_var,' ',student_lname_var)AS student, prog.program_id,cat.categoryName,evt.eventName FROM campus_student cs JOIN campus_event_studentregistration st ON cs.student_admissionno_var = st.captain_admissionNo JOIN campus_event_registration evt ON evt.event_Id = st.event_id JOIN campus_event_category cat ON cat.categoryId = st.category_id JOIN campus_event_programcreation prog ON prog.program_id = st.program_id where st.captain_admissionNo=?";

	
	public static String GET_PARTICPANT_LIST_FROM_EVENT_REGISTRATION1="SELECT ces.*,h.housename,cer.`eventName`,cer.`event_Id`,cec.`categoryName`,cec.`categoryId`,cep.`program_name`,cep.`program_id` FROM campus_event_studentregistration ces LEFT JOIN campus_house_settings h ON h.house_id=ces.house_id LEFT JOIN `campus_event_registration` cer ON cer.`event_Id`=ces.`event_id` LEFT JOIN `campus_event_category` cec ON cec.`categoryId`=ces.`category_id` AND cec.`eventId`=ces.`event_id` LEFT JOIN `campus_event_programcreation` cep ON cep.`program_id`=ces.`program_id` AND cep.`event_id`=ces.`event_id` AND cep.`category_id`=ces.`category_id` WHERE ces.event_id LIKE ? AND ces.category_id LIKE ? AND ces.program_id LIKE ?";
	public static String GET_EVENT_PRINT_DETAILS="SELECT ces.*,h.housename,cer.`eventName`,cec.`categoryName`,cep.`program_name` FROM campus_event_studentregistration ces LEFT JOIN campus_house_settings h ON h.house_id=ces.house_id LEFT JOIN `campus_event_registration` cer ON cer.`event_Id`=ces.`event_id` LEFT JOIN `campus_event_category` cec ON cec.`categoryId`=ces.`category_id` AND cec.`eventId`=ces.`event_id` LEFT JOIN `campus_event_programcreation` cep ON cep.`program_id`=ces.`program_id` AND cep.`event_id`=ces.`event_id` AND cep.`category_id`=ces.`category_id` WHERE ces.event_id LIKE ? AND ces.category_id LIKE ? AND ces.program_id LIKE ?";

	public static final String GET_PROGRAM_NAME ="SELECT program_id,program_name FROM campus_event_programcreation WHERE event_id LIKE ? AND category_id LIKE ?";
	public static String GET_PARTICPANT_ROLLNO="SELECT cs.`student_id_int` FROM `campus_student` cs WHERE cs.`student_admissionno_var`=?";

	
	/*public static String getProgramNumberingDetails="SELECT st.category_id,CONCAT(student_fname_var,' ',student_lname_var)AS student, prog.program_id,cat.categoryName,evt.eventName FROM campus_student cs JOIN campus_event_studentregistration st ON cs.student_admissionno_var = st.captain_admissionNo JOIN campus_event_registration evt ON evt.event_Id = st.event_id JOIN campus_event_category cat ON cat.categoryId = st.category_id JOIN campus_event_programcreation prog ON prog.program_id = st.program_id where st.captain_admissionNo=?";*/


	/*public static String GET_PARTICPANT_LIST_FROM_EVENT_REGISTRATION1="SELECT ces.*,h.housename,cer.`eventName`,cec.`categoryName`,cep.`program_name` FROM campus_event_studentregistration ces LEFT JOIN campus_house_settings h ON h.house_id=ces.house_id LEFT JOIN `campus_event_registration` cer ON cer.`event_Id`=ces.`event_id` LEFT JOIN `campus_event_category` cec ON cec.`categoryId`=ces.`category_id` AND cec.`eventId`=ces.`event_id` LEFT JOIN `campus_event_programcreation` cep ON cep.`program_id`=ces.`program_id` AND cep.`event_id`=ces.`event_id` AND cep.`category_id`=ces.`category_id` WHERE ces.event_id LIKE ? AND ces.registration_id LIKE ?";*/
	public static String saveProgramNumberingDetails="insert into campus_event_program_numbering(program_number_id,regId,stageId,event,category,program,participants,programnumber) values (?,?,?,?,?,?,?,?)";

/*	public static String GET_PARTICPANT_LIST_FROM_EVENT_REGISTRATION1="SELECT ces.*,h.housename,cer.`eventName`,cec.`categoryName`,cep.`program_name` FROM campus_event_studentregistration ces LEFT JOIN campus_house_settings h ON h.house_id=ces.house_id LEFT JOIN `campus_event_registration` cer ON cer.`event_Id`=ces.`event_id` LEFT JOIN `campus_event_category` cec ON cec.`categoryId`=ces.`category_id` AND cec.`eventId`=ces.`event_id` LEFT JOIN `campus_event_programcreation` cep ON cep.`program_id`=ces.`program_id` AND cep.`event_id`=ces.`event_id` AND cep.`category_id`=ces.`category_id` WHERE ces.event_id LIKE ? AND ces.registration_id LIKE ?";
*/	/*public static String saveProgramNumberingDetails="insert into campus_event_program_numbering(stageId,event,category,program,participants,programnumber) values (?,?,?,?,?,?)";*/

	public static String getStageParticipant="select ParticipantsName from campus_event_stage_allocation where Event=? and StageName=?";
	public static String getMappedProgramNumberingDetails="select concat(cs.student_fname_var,cs.student_lname_var) as name,pro.program_name,cat.categoryName,nmbr.program_number_id,nmbr.regId,nmbr.stageId,nmbr.event,nmbr.category,nmbr.program,nmbr.participants,nmbr.programnumber  from campus_event_program_numbering nmbr join campus_student cs on cs.student_admissionno_var=nmbr.participants join campus_event_category cat on cat.categoryId=nmbr.category join campus_event_programcreation pro on pro.program_id=nmbr.program   where  event=? and stageId=? order by  length(nmbr.programnumber),nmbr.programnumber asc";
	public static String deleteProgramNumber="DELETE  FROM `campus_event_program_numbering` WHERE `program_number_id` =?";
	public static String deleteAllProgramNumber="delete  from `campus_event_program_numbering`  WHERE `event`=? AND `stageId`=?";

	//Volanteer Registration and ChestNo Generation

	
	public static String countProgramNumber="delete  from campus_event_program_numbering where program_number_id=?";

	public static final String GET_PARTICPANT_CHESTNO_FOR_GENERATING_NO_FROM_STUDENT_REGISTRATION="SELECT ecnl.*,l.`Location_Name`,cs.*,csc.*,csc.student_imgurl_var imgurl_var,ecnl.chest_no FROM campus_student cs  JOIN campus_student_classdetails csc ON csc.student_id_int=cs.student_id_int  JOIN campus_classdetail cc ON (cc.classdetail_id_int=csc.classdetail_id_int AND cc.locationId=csc.locationId) JOIN `campus_location` l ON l.`Location_Id`=cs.`locationId` JOIN campus_event_chestno_list ecnl ON ecnl.admission_no=cs.student_admissionno_var  WHERE ecnl.admission_no=? ORDER BY ecnl.chest_no * 1 ASC";

	public static final String SAVE_CHEST_NO_REGISTRATION = "INSERT INTO campus_event_chestnumber(chestnumber_id,event_id,category_id,program_id) VALUES(?,?,?,?)";
	public static final String UPDATE_CHESTNO_GENERATION ="UPDATE campus_event_chestnumber SET event_id=?,category_id=?,program_id=? WHERE chestnumber_id=?";
	public static final String GET_CHESTNO_REGISTRATION_LIST ="SELECT cecn.chestnumber_id,cecn.event_id,cecn.category_id,cecn.program_id,cer.eventName,cec.categoryName,cep.program_name,ces.stageName,cep.programDate FROM campus_event_chestnumber cecn  JOIN campus_event_registration cer ON cecn.event_id=cer.event_Id JOIN campus_event_category cec ON cec.categoryId=cecn.category_id JOIN campus_event_programcreation cep ON cep.program_id=cecn.program_id JOIN campus_event_stage ces ON ces.eventId=cecn.event_id WHERE  cecn.event_id LIKE ? AND cecn.category_id LIKE ? AND cecn.program_id LIKE ?";
	public static String DELETE_CHESTNO_GENERATION="DELETE FROM campus_event_chestnumber WHERE chestnumber_id=?";
	public static final String GET_DATA_FOR_UPDATE_CHESTNO_GENERATION ="select  event_id,category_id,program_id from campus_event_chestnumber WHERE chestnumber_id=?";
	public static final String GET_CHESTNO_LIST ="SELECT cesr.participants_admissionNo  FROM  campus_event_studentregistration cesr JOIN campus_event_chestnumber cec ON(cec.event_id=cesr.event_id AND cec.category_id=cesr.category_id AND cec.program_id=cesr.program_id) WHERE cesr.event_id=? AND cesr.category_id=? AND cesr.program_id=?";
	public static final String GET_STUDENTS_CHESTNO_LIST ="SELECT cs.*,csc.*,cc.* FROM campus_student cs LEFT JOIN campus_student_classdetails csc ON csc.student_id_int=cs.student_id_int LEFT JOIN campus_classdetail cc ON (cc.classdetail_id_int=csc.classdetail_id_int AND cc.locationId=csc.locationId) LEFT JOIN `campus_location` l ON l.`Location_Id`=cs.`locationId` WHERE cs.student_admissionno_var=?";

	//Volanteer Registration
		public static final String GET_VOLANTEER_LIST = "SELECT v.volunteer_id,v.admission_no,CONCAT(cs.`student_fname_var`,'',cs.student_lname_var) AS student,g.greenroom_name,s.stageName,v.start_time,v.end_time FROM campus_event_volunteerregistation v  LEFT JOIN campus_event_greenroom g ON g.greenroom_id=v.greenroom_id  LEFT JOIN campus_student cs ON  cs.student_admissionno_var=v.admission_no LEFT JOIN campus_event_stage s ON s.stageId=v.stage_id  WHERE v.loc_id LIKE ? AND v.event_id LIKE ?";
		public static final String DELETE_VOLNTEER = "delete FROM campus_event_volunteerregistation where volunteer_id=?";
		//public static final String UPDATE_VOLANTEER_REGISTRATION_DETAIL ="SELECT cev.`stage_id`,cev.`greenroom_id`, cev.event_id,cev.loc_id,cev.admission_no,cev.volunteer_name,ceg.greenroom_name,ces.stageName,cev.start_time,cev.end_time FROM campus_event_volunteerregistation cev JOIN campus_event_greenroom ceg ON ceg.greenroom_id=cev.greenroom_id JOIN campus_event_stage ces ON ces.stageId=cev.stage_id WHERE volunteer_id=?";
		public static final String update = "SELECT v.stage_id,v.volunteer_id,CONCAT(v.admission_no,'-',cs.student_fname_var,'',cs.student_lname_var) AS AdmissionNo,v.event_id,loc_id,v.greenroom_id,v.start_time,v.end_time FROM campus_event_volunteerregistation v LEFT JOIN campus_student cs ON  cs.student_admissionno_var=v.admission_no  WHERE `volunteer_id`=?";
		public static final String GET_ADMISSION_NO = "SELECT student_admissionno_var FROM campus_student WHERE student_admissionno_var LIKE ?";
		public static final String GET_VOLANTEER_BY_ADMISSION_NO ="SELECT student_admissionno_var,CONCAT(student_fname_var,' ',student_lname_var) AS student FROM campus_student WHERE (student_admissionno_var LIKE ? OR student_fname_var LIKE ?) AND student_admissionno_var NOT IN(SELECT admission_no FROM campus_event_volunteerregistation)";
		public static final String GET_EVENT_NAME = "SELECT event_Id,eventName FROM campus_event_registration";/* WHERE event_Id LIKE ?*/
		public static final String GET_PARTICPANT_CHESTNO_LIST_FROM_EVENT_REGISTRATION = "SELECT captain_admissionNo FROM  campus_event_studentregistration WHERE event_id LIKE ? AND category_id LIKE ? AND program_id LIKE ?";
		public static final String getcatagorysList = "select categoryId,categoryName from campus_event_category where eventId=?";
		public static final String getprogramList = "select program_id,program_name from campus_event_programcreation where  event_id =? AND `category_id`=?";
		public static final String getEventParticipantseventList = "SELECT DISTINCT CONCAT(st.student_fname_var,' ',st.student_lname_var)AS student,et.event_Id,et.eventName,ec.categoryName, pr.program_name,sta.stageName FROM campus_student st JOIN campus_event_studentregistration est JOIN campus_event_registration et ON et.event_Id = est.event_id JOIN campus_event_category ec ON ec.categoryId = est.category_id JOIN campus_event_programcreation pr ON pr.program_id = est.program_id JOIN campus_event_stage_allocation stall ON  stall.Event = est.event_id JOIN campus_event_stage sta ON sta.eventId = stall.Event  where  et.eventName=?";
		public static final String getEventParticipantssearchList = "SELECT DISTINCT CONCAT(st.student_fname_var,' ',st.student_lname_var)AS student, et.event_Id,et.eventName,ec.categoryName,pr.program_name,sta.stageName FROM campus_student st JOIN campus_event_studentregistration est JOIN campus_event_registration et ON et.event_Id = est.event_id JOIN campus_event_category ec ON ec.categoryId = est.category_id JOIN campus_event_programcreation pr ON pr.program_id = est.program_id JOIN campus_event_stage sta ON sta.eventId = est.event_id JOIN campus_event_stage_allocation stall ON sta.stageId = stall.StageName or stall.Event = est.event_id WHERE et.event_Id LIKE ? AND ec.categoryId LIKE ? AND sta.stageId LIKE ? AND pr.program_id LIKE ? AND(st.student_fname_var like ? OR et.eventName like ? OR ec.categoryName like ? OR pr.program_name like ? OR sta.stageName like ? )";
		public static final String GET_TABLE = "SELECT `participants_admissionNo` FROM `campus_event_studentregistration` WHERE `event_id`=? AND `category_id`=? AND `program_id`=?";
		public static final String CHECK_HOUSE_WISE = "SELECT `isHouseWise` FROM `campus_event_programcreation` WHERE `program_id`=? AND`event_id`=? AND `category_id`=?";
		public static final String GET_PARTICPANT_HOUSE_WISE = "SELECT l.`Location_Name`,cs.*,csc.*,cs.`student_id_int`,csc.student_rollno rollNo,csc.student_imgurl_var imgurl_var,cc.classdetails_name_var,css.`classsection_name_var`FROM campus_student cs LEFT JOIN campus_student_classdetails csc ON csc.student_id_int=cs.student_id_int LEFT JOIN campus_classdetail cc ON (cc.classdetail_id_int=csc.classdetail_id_int AND cc.locationId=csc.locationId) LEFT JOIN campus_classsection css ON (css.`classsection_id_int`=csc.`classsection_id_int` AND css.locationId=csc.locationId) LEFT JOIN `campus_location` l ON l.`Location_Id`=cs.`locationId`  WHERE cs.student_admissionno_var=? AND csc.fms_acadamicyear_id_int=?";
		public static final String PARTICIPATORS_LIST = "SELECT * FROM `campus_event_marksentry` WHERE `event_id`=? AND `category_id`=? AND `program_id`=? AND `AccYear`=? ORDER BY `scoredMarks` * 1  DESC  LIMIT 100 OFFSET 3";
		public static final String GET_PARTICIPATED_STUDENTS = "SELECT l.`Location_Name`,cs.*,csc.*,cs.`student_id_int`,csc.student_rollno rollNo,csc.student_imgurl_var imgurl_var,cc.classdetails_name_var,css.`classsection_name_var`FROM campus_student cs LEFT JOIN campus_student_classdetails csc ON csc.student_id_int=cs.student_id_int LEFT JOIN campus_classdetail cc ON (cc.classdetail_id_int=csc.classdetail_id_int AND cc.locationId=csc.locationId) LEFT JOIN campus_classsection css ON (css.`classsection_id_int`=csc.`classsection_id_int` AND css.locationId=csc.locationId) LEFT JOIN `campus_location` l ON l.`Location_Id`=cs.`locationId` WHERE cs.student_admissionno_var=(SELECT `admission_no` FROM `campus_event_chestno_list` WHERE `chest_no`=?) AND csc.fms_acadamicyear_id_int=?";
		public static final String GET_TOP_PARTICIPATORS_LIST = "SELECT * FROM `campus_event_marksentry` WHERE `event_id`=? AND `category_id`=? AND `program_id`=? AND `AccYear`=? ORDER BY `scoredMarks` * 1 DESC LIMIT 3";
		public static final String  GET_PARTICPANT_CHESTNO_LIST_FROM_STUDENT_REGISTRATION="SELECT DISTINCT cecn.*,l.`Location_Name`,cs.*,csc.*,csc.student_imgurl_var imgurl_var FROM campus_student cs  JOIN campus_student_classdetails csc ON csc.student_id_int=cs.student_id_int JOIN campus_classdetail cc ON (cc.classdetail_id_int=csc.classdetail_id_int AND cc.locationId=csc.locationId) JOIN campus_location l ON l.`Location_Id`=cs.`locationId`  JOIN campus_event_chestno_list cecn ON cs.student_admissionno_var=cecn.admission_no JOIN campus_event_registration cer ON cer.accyer_ID=csc.fms_acadamicyear_id_int JOIN campus_event_category cec ON cec.eventId=cer.event_Id JOIN campus_event_programcreation cep ON (cep.event_id=cer.event_Id AND cep.category_id=cec.categoryId) WHERE cecn.admission_no =? AND cer.event_Id LIKE ? AND cec.categoryId LIKE ? AND cep.program_id LIKE ? ORDER BY cecn.chest_no * 1 ASC";
	    public static String GET_PARTICPANTLIST_FROM_EVENT_REGISTRATION="SELECT l.`Location_Name`,cs.*,csc.*, csc.student_rollno rollNo,csc.student_imgurl_var imgurl_var,cc.classdetails_name_var FROM campus_student cs LEFT JOIN campus_student_classdetails csc ON csc.student_id_int=cs.student_id_int LEFT JOIN campus_classdetail cc ON (cc.classdetail_id_int=csc.classdetail_id_int AND cc.locationId=csc.locationId) LEFT JOIN `campus_location` l ON l.`Location_Id`=cs.`locationId`  WHERE cs.student_admissionno_var=? AND cs.student_id_int=? ";
	    public static String getEventParticipantsList="SELECT ces.*,h.housename FROM campus_event_studentregistration ces LEFT JOIN campus_house_settings h ON h.house_id=ces.house_id WHERE event_id LIKE ? AND `category_id` LIKE ? AND `program_id` LIKE ?  AND `participateType`='group'";
		public static String getProgrammeDate="SELECT `Program_date` FROM `campus_event_program_scheduling` WHERE `Event_name`=? AND `Program_name`=? AND `Stage`=?";
	    public static String getProgramScheduledList_eventId="SELECT sc.`Makeup_report`,sc.`BackStage_report`,sc.Program_time,reg.eventName,reg.event_Id,pgrm.program_id,pgrm.program_name,pgrm.programDate,stg.stageId,stg.stageName,grn.greenroom_id,grn.greenroom_name FROM campus_event_registration reg    JOIN campus_event_programcreation pgrm ON pgrm.event_id=reg.event_Id   JOIN campus_event_stage stg ON stg.eventId=reg.event_Id JOIN campus_event_greenroom grn ON grn.event_id=reg.event_Id JOIN `campus_event_program_scheduling` sc ON sc.`Event_name`=reg.`event_Id` AND sc.`Program_name`=pgrm.`program_id` AND sc.`Stage`=stg.`stageId` AND sc.`Green_room`=grn.`greenroom_id` where reg.event_Id like ? ORDER BY pgrm.programDate,reg.eventName,pgrm.program_name ";
	    public static String getProgramScheduledList_progDate="SELECT sc.`Makeup_report`,sc.`BackStage_report`,sc.Program_time,reg.eventName,reg.event_Id,pgrm.program_id,pgrm.program_name,pgrm.programDate,stg.stageId,stg.stageName,grn.greenroom_id,grn.greenroom_name FROM campus_event_registration reg  JOIN campus_event_programcreation pgrm ON pgrm.event_id=reg.event_Id   JOIN campus_event_stage stg ON stg.eventId=reg.event_Id JOIN campus_event_greenroom grn ON grn.event_id=reg.event_Id  JOIN `campus_event_program_scheduling` sc ON sc.`Event_name`=reg.`event_Id` AND sc.`Program_name`=pgrm.`program_id` AND sc.`Stage`=stg.`stageId` AND sc.`Green_room`=grn.`greenroom_id` where reg.event_Id like ? and programDate like ? ORDER BY pgrm.programDate,reg.eventName,pgrm.program_name";
	    public static String getProgramNumberingList="SELECT  num.`programnumber`,stg.`stageName`,st.registration_id,prog.program_name,st.category_id,CONCAT(student_fname_var,' ',student_lname_var)AS student, prog.program_id,cat.categoryName,evt.eventName  FROM `campus_event_program_numbering` num   JOIN `campus_event_registration` evt  ON evt.event_Id=num.`event`  JOIN  campus_event_category cat ON cat.categoryId=num.`category` AND evt.event_Id = cat.eventId JOIN `campus_event_stage` stg ON stg.`stageId`=num.`stageId` AND evt.event_Id = stg.eventId  JOIN  campus_event_programcreation prog ON prog.program_id=num.`program` AND cat.categoryId = prog.category_id JOIN `campus_event_studentregistration`st ON  st.captain_admissionNo =num.`participants` AND st.event_id = num.`event` AND st.category_id = num.category AND st.`program_id`=num.`program`  JOIN  campus_student cs ON cs.`student_admissionno_var`=num.`participants` WHERE num.`event`=? AND num.`stageId`=? ORDER BY   num.programnumber";
	    public static String getStageAllocatedParticipants="SELECT  al.Event,CONCAT(cs.`student_fname_var`,'',cs.`student_lname_var`) AS student,ev.`eventName`,stg.`stageName`,prg.`program_name`,cat.`categoryName` FROM `campus_event_stage_allocation`  al  JOIN `campus_student` cs ON cs.`student_admissionno_var`=al.`ParticipantsName` JOIN `campus_event_registration` ev ON  ev.`event_Id`=al.`Event` JOIN `campus_event_stage` stg ON stg.`stageId`=al.`StageName` JOIN  `campus_event_programcreation` prg ON prg.`event_id`=al.Event JOIN `campus_event_category` cat ON cat.`eventId`=al.Event WHERE al.Event=? AND al.`StageName`=?";
	    public static String getListforCriteria="SELECT cat.`categoryId`,cat.`categoryName`,reg.eventName,reg.event_Id,pgrm.program_id,pgrm.program_name,pgrm.programDate FROM campus_event_registration reg  JOIN campus_event_programcreation pgrm ON pgrm.event_id=reg.event_Id JOIN `campus_event_category` cat ON cat.`categoryId`=pgrm.`category_id`  WHERE reg.event_Id LIKE ? AND pgrm.`category_id` LIKE ? AND pgrm.program_id LIKE ?  ORDER BY pgrm.programDate,reg.eventName,pgrm.program_name";
	    public static final String GET_CRITERIA_FOR_JUDGEMENTSHEET ="SELECT `Criteria`,`Max_marks` FROM `campus_event_criteria` WHERE `Event_id`=? AND `Programme_Name`=? AND `Category`=?";
	    public static String GET_MERIT_PARTICPANT_LIST="SELECT * FROM `campus_event_marksentry` WHERE `scoredMarks`>=(SELECT `scoredMarks`FROM `campus_event_marksentry` cme1 WHERE (3-1) =( SELECT COUNT(DISTINCT(cme2.`scoredMarks`)) FROM `campus_event_marksentry` cme2 WHERE cme2.`scoredMarks` > cme1.`scoredMarks`)) AND `event_id`=? AND `category_id`=? AND `program_id`=? AND `AccYear`=? ORDER BY `scoredMarks` DESC";  
	    
	    //chest No
		public static final String PRINT_CHEST_NO = "SELECT participants_admissionNo FROM campus_event_studentregistration st JOIN  campus_event_registration evt ON evt.event_Id = st.event_id JOIN campus_event_category cat ON cat.categoryId = st.category_id JOIN campus_event_programcreation prg ON prg.program_id = st.program_id WHERE accId = ? AND evt.event_Id LIKE ? AND cat.categoryId LIKE ? AND prg.program_id LIKE ?";
		public static final String PRINT_CHEST_NOS ="SELECT chest_no,CONCAT(student_fname_var,' ',student_lname_var) AS student,Location_Name FROM campus_student st JOIN campus_student_classdetails csc ON st.student_id_int = csc.student_id_int JOIN campus_location ON Location_Id = st.locationId JOIN campus_event_chestno_list ON admission_no = st.student_admissionno_var WHERE admission_no = ?";
		public static final String GET_PARTICPANT_HOUSE_WISE_1 ="SELECT cep.program_name,l.`Location_Name`,cs.*,csc.*,cs.`student_id_int`,csc.student_rollno rollNo,csc.student_imgurl_var imgurl_var,cc.classdetails_name_var,css.`classsection_name_var`FROM campus_student cs LEFT JOIN campus_student_classdetails csc ON csc.student_id_int=cs.student_id_int LEFT JOIN campus_classdetail cc ON (cc.classdetail_id_int=csc.classdetail_id_int AND cc.locationId=csc.locationId) LEFT JOIN campus_classsection css ON (css.`classsection_id_int`=csc.`classsection_id_int` AND css.locationId=csc.locationId) LEFT JOIN `campus_location` l ON l.`Location_Id`=cs.`locationId` JOIN campus_event_studentregistration s ON cs.student_admissionno_var=s.participants_admissionNo JOIN `campus_event_programcreation` cep ON cep.program_id=s.`program_id`  WHERE cs.student_admissionno_var=? AND csc.fms_acadamicyear_id_int=? AND csc.student_house=?";
}
