package com.centris.campus.util;

public class ReportsMenuSqlConstants {

	//fee report
	public static final String Get_Fee_Report ="SELECT st.student_fname_var,cfc.admissionNo studentId,cft.termname,cfc.termcode,cfc.totalamount,cfc.actualamount paidamount,cfc.paidDate,cfc.is_paid FROM campus_fee_collection cfc LEFT JOIN campus_student st ON cfc.admissionNo=st.student_id_int LEFT JOIN campus_fee_termdetails cft ON cfc.termcode=cft.termid WHERE cfc.accYear=? AND st.classdetail_id_int=? AND st.classsection_id_int=? AND paidDate>=? AND paidDate<=?";
	//public static final String GET_SELECTED_ITEMS_FEE = "select acc.acadamic_year,s.classstream_name_var,c.classdetails_name_var,sec.classsection_name_var,Location_Name from campus_acadamicyear acc,campus_classstream s,campus_classdetail c,campus_classsection sec,campus_location where acc.acadamic_id=? and s.classstream_id_int=? and c.classdetail_id_int=? and sec.classsection_id_int like ? and Location_Id=?";
	
	
	//Student Information Report queries written by seshu
	
	public static final String GET_ACCYEAR = "select acadamic_id,acadamic_year from campus_acadamicyear order by startDate";
	public static final String GET_STREAMS = "select classstream_id_int,classstream_name_var from campus_classstream";
	public static final String GET_CLASSES = "select classdetail_id_int,classdetails_name_var from campus_classdetail where classstream_id_int like ? order by length(classdetail_id_int),classdetail_id_int asc";
	public static final String GET_SECTIONS = "select distinct classsection_id_int,classsection_name_var from campus_classsection where classdetail_id_int =? and locationId=?  order by classsection_name_var ";
	
	public static final String GET_STUDENTSiNFORMATION = "select st.student_id_int,student_admissionno_var,concat(student_fname_var,' ',student_lname_var) as studentname,student_age_int,student_doj_var,FatherName,mobileno, student_mothername_var,student_mothermobileno_var from campus_student st,campus_parents p,campus_parentchildrelation pc where pc.stu_addmissionNo=st.student_id_int and pc.parentid=p.ParentID and fms_acadamicyear_id_int=?  and fms_classstream_id_int=? and classdetail_id_int=? and classsection_id_int=? and st.student_status_var='active'"; 
	
	public static final String GET_SELECTED_ITEMS = "select acc.acadamic_year,s.classstream_name_var,c.classdetails_name_var,sec.classsection_name_var,Location_Name from campus_acadamicyear acc,campus_classstream s,campus_classdetail c,campus_classsection sec,campus_location where acc.acadamic_id=? and s.classstream_id_int=? and c.classdetail_id_int=? and sec.classsection_id_int like ? and Location_Id=?";
	
	public static final String GET_CLASS = "select classdetail_id_int,classdetails_name_var from campus_classdetail where locationId = ? order by length(classdetail_id_int),classdetail_id_int asc";
	
	
	
	//Staff Attendance Information Report queries 
	public static final String GET_STAFF_ATTENDANCE_ITEMS = "select acadamic_year,acadamic_id from campus_acadamicyear where acadamic_id=?";
	public static final String GET_TEACHINGTYPE_LIST = "select concat(tea.FirstName,' ',LastName) as teachername ,att.AttendenceDate,att.AttendenceStatus from campus_teachers tea,campus_teacher_attendence att where att.TeacherID=tea.TeacherID and tea.teachingType='Teaching' and tea.isActive='Y' and att.AttendenceDate between ? and ? and tea.TeacherID like ?";
	 
	public static final String GET_NON_TEACHINGTYPE_LIST = "select concat(tea.FirstName,' ',LastName) as teachername ,att.AttendenceDate,att.AttendenceStatus from campus_teachers tea,campus_teacher_attendence att where att.TeacherID=tea.TeacherID and tea.teachingType='Non-Teaching' and tea.isActive='Y' and att.AttendenceDate between ? and ? and tea.TeacherID like ?";
	public static final String GET_STAFF_TEACHING_LIST = "select TeacherID,concat(FirstName,' ',LastName) as teachername from campus_teachers where teachingType='Teaching' and isActive='Y'";
	public static final String GET_STAFF_NON_TEACHING_LIST = "select TeacherID,concat(FirstName,' ',LastName) as teachername from campus_teachers where teachingType='Non-Teaching' and isActive='Y'";
	public static final String TEACHER_NAMES = "select TeacherID,concat(FirstName,' ',LastName)as teachername from campus_teachers where TeacherID=?";
	
	
	
	
	//student Attendance
	public static final String GET_STUDENT_ATTENDANCE_LIST = "select concat(st.student_fname_var,' ',student_lname_var) as studentname ,str.classstream_name_var,cls.classdetails_name_var, sec.classsection_name_var,att.attendencedate,att.attendence,acc.acadamic_year from campus_student st JOIN campus_student_classdetails csc ON st.student_id_int=csc.student_id_int JOIN campus_classstream str ON csc.fms_classstream_id_int=str.classstream_id_int JOIN campus_classdetail cls ON csc.classdetail_id_int=cls.classdetail_id_int AND csc.locationId=cls.locationId JOIN campus_classsection sec ON csc.classsection_id_int=sec.classsection_id_int JOIN campus_attendence att ON csc.student_id_int=att.addmissionno JOIN campus_acadamicyear acc ON csc.fms_acadamicyear_id_int=acc.acadamic_id  where att.attendencedate between ? and ? and csc.student_id_int like ? and csc.student_status='STUDYING'"; 
	public static final String GET_STREAM_NAME = "select classstream_name_var,classstream_id_int from campus_classstream where classstream_id_int=?";
	public static final String GET_CLASS_NAME = "select classdetail_id_int,classdetails_name_var from campus_classdetail where classdetail_id_int =?";
	public static final String GET_SECTION_NAME = "select classsection_id_int,classsection_name_var from campus_classsection where classsection_id_int=?";
	public static final String GET_STUDENT_NAME = "select student_id_int, concat(student_fname_var,' ',student_lname_var)as studentname from campus_student where student_id_int=?";
	
	
	//Staff Releiving Order
	public static final String GET_TEACHER_TEACHING_LIST = "select TeacherID,concat(FirstName,' ',LastName) as teachername from campus_teachers where teachingType='Teaching' and isActive='Y' and role=?";
	public static final String GET_NONTEACHER_TEACHING_LIST = "select TeacherID,concat(FirstName,' ',LastName) as teachername from campus_teachers where teachingType='Non-Teaching' and isActive='Y' and role=?";
	public static final String GET_USER_LIST = "select RoleCode,RoleName from campus_role order by RoleName";
	public static final String GET_RELEIVING_DETAILS_LIST = "select concat(t.FirstName,' ',LastName)as teachername,t.registerId,t.dateofJoining,des.designationName,sl.EmployeePfNo,sl.CTC from campus_teachers t,campus_designation des, campus_staff_salarydetails sl where t.designation=des.DesignationCode and t.TeacherID=? and t.TeacherID=sl.TeacherID and (SELECT  MAX( sl.CreateDate)FROM campus_staff_salarydetails sl)";
	
	//student Transfer Certificate 
	public static final String GET_CLASS_DETAILS = "select classdetail_id_int,classdetails_name_var from campus_classdetail order by classdetail_id_int";
	public static final String GET_SECTION_DETAILS = "select classsection_id_int,classsection_name_var from campus_classsection where classdetail_id_int=? and locationId=? order by classsection_name_var";
	public static final String GET_STUDENT_DETAILS = "select student_id_int,concat(student_fname_var,' ',student_lname_var) as studentname from campus_student where classsection_id_int=? and student_status_var='active' order by student_fname_var";
	
	
	//Phone Directory
	
	public static final String GET_ADMIN_LIST = "select tea.TeacherID,concat(tea.FirstName,' ',LastName) as adminname,rl.RoleName from campus_teachers tea,campus_role  rl where tea.role=rl.RoleCode and RoleName='Admin' and tea.isActive='Y'";
	public static final String GET_STUDENTS_LIST = "select student_id_int,concat(student_fname_var,' ',student_lname_var)as studentname from campus_student where student_status_var ='active' order by student_fname_var";
	public static final String GET_TEACHERS_LIST = "select tea.TeacherID,concat(tea.FirstName,' ',LastName) as teachername,rl.RoleName from campus_teachers tea,campus_role  rl where tea.role=rl.RoleCode and RoleName='Teacher' and tea.isActive='Y'";
	public static final String  GET_ALL_TEACHERS_LIST = "select TeacherID,concat(FirstName,' ',LastName) as teachername from campus_teachers order by FirstName";
	public static final String GET_ADMIN_PHONE_DIRECTORYLIST = "select tea.TeacherID,concat(tea.FirstName,' ',LastName) as adminname,rl.RoleName,tea.mobileNo,tea.emailId,tea.permanentAddress from campus_teachers tea,campus_role  rl where tea.role=rl.RoleCode and RoleName='Admin' and tea.TeacherID like ?";
	public static final String GET_STUDENTSPHONE_DIRECTORY_LIST = "select pr.parentid,st.student_id_int,concat(st.student_fname_var,' ',st.student_lname_var)as studentname,case when (p.mobileno is null || p.mobileno='') then p.student_gardian_mobileno else p.mobileno end FatherMobile,case when (p.email is null || p.email='') then p.student_gardian_mailid else p.email end FatherMailId,p.address from campus_student st,campus_parents p,campus_parentchildrelation pr where pr.stu_addmissionNo=st.student_id_int and pr.parentid=p.ParentID and st.student_id_int like ? order by student_fname_var";
	public static final String GET_TEACHERS_PHONE_DIRECTORY_LIST = "select tea.TeacherID,concat(tea.FirstName,' ',LastName) as teachername,rl.RoleName,tea.mobileNo,tea.emailId,tea.permanentAddress from campus_teachers tea,campus_role  rl where tea.role=rl.RoleCode and RoleName='Teacher' and tea.TeacherID like ?";
	public static final String GET_ALL_TEACHERS_DIRECTORY_LIST = "select tea.TeacherID,concat(tea.FirstName,' ',LastName) as teachername,rl.RoleName,tea.mobileNo,tea.emailId,tea.permanentAddress from campus_teachers tea,campus_role  rl where tea.role=rl.RoleCode  and tea.TeacherID like ?";
	public static final String GET_ALL_STUDENTSPHONE_DIRECTORY_LIST = "select pr.parentid,st.student_id_int,concat(st.student_fname_var,' ',st.student_lname_var)as studentname,case when (p.mobileno is null || p.mobileno='') then p.student_gardian_mobileno else p.mobileno end FatherMobile,case when (p.email is null || p.email='') then p.student_gardian_mailid else p.email end FatherMailId,p.address from campus_student st,campus_parents p,campus_parentchildrelation pr where pr.stu_addmissionNo=st.student_id_int and pr.parentid=p.ParentID order by student_fname_var";

	public static final String GET_ALL_STUDENTSPHONE_DIRECTORY_LIST1 = "select student_id_int,concat(student_fname_var,' ',student_lname_var)as studentname,case when (student_fathermobileno_var is null || student_fathermobileno_var='') then student_gardian_mobileno else student_fathermobileno_var end FatherMobile,case when (student_father_mailid is null || student_father_mailid='') then student_gardian_mailid else student_father_mailid end FatherMailId,student_address from campus_student  where student_id_int like ?";
	public static final String GET_ALL_TEACHERS_DIRECTORY_LIST1 = "select tea.TeacherID,concat(tea.FirstName,' ',LastName) as teachername,rl.RoleName,tea.mobileNo,tea.emailId,tea.permanentAddress from campus_teachers tea,campus_role  rl where tea.role=rl.RoleCode  and tea.TeacherID like ?";
	public static final String GET_TEACHERS_NAME = "select TeacherID,concat(FirstName,' ',LastName) as teachername from campus_teachers where TeacherID=?";
	public static final String GET_STUDENTS_NAME = "select student_id_int,concat(student_fname_var,' ',student_lname_var) as studentname from campus_student where student_id_int=?";
	
	//Service Certificate
	
		public static final String GET_TEACHER_DETAILS = "select TeacherID,concat(FirstName,' ',LastName)as teachername from campus_teachers where isActive = 'Y' order by FirstName";
		public static final String GET_TEACHER_DETAILS_BY_ID = "select tea.TeacherID,concat(tea.FirstName,' ',LastName) as teachername,tea.dateofJoining,des.designationName from campus_teachers tea,campus_designation des where tea.designation=des.DesignationCode and tea.TeacherID=?";
		
	
	// For FeeCollectionSummaryReport written by seshu
	
	public static final String GET_TOT_CLASSFEE="select concat(cd.classdetails_name_var,' - ',cs.classsection_name_var)ClassName,ft.termname,sum(fstd.feeAmount)ActualAmount,st.classdetail_id_int ClassId,st.classsection_id_int SectionId from campus_student st,campus_fee_setup fst, campus_fee_setupdetails fstd,campus_fee_master fm,campus_fee_termdetails ft,campus_classdetail cd,campus_classsection cs where st.classdetail_id_int=fst.ClassCode and fstd.feeSettingCode=fst.feeSettingcode and fm.FeeCode=fstd.feecode and fst.Termcode=ft.termid and cd.classdetail_id_int=st.classdetail_id_int and cs.classsection_id_int=st.classsection_id_int and  st.classdetail_id_int=? and st.classsection_id_int=? and fst.AccyearCode=? and fst.Termcode=? and st.student_status_var='active'";
	public static final String GET_TOT_TRANSPORTFEE="select sum(fstgd.feeAmount)transportfee from campus_fee_stagesetup fstg,campus_fee_stagesetupdetails fstgd,campus_student st where st.classdetail_id_int=? and st.classsection_id_int=? and st.student_status_var='active' and fstg.ClassCode=st.classdetail_id_int and fstg.stageSettingCode=fstgd.stageSettingCode and fstg.AccyearCode=? and fstg.Termcode=?";
	public static final String GET_TOT_PAID_FEE = "SELECT sum(fc.actualamount)paidfee from campus_fee_collection fc,campus_student st where fc.admissionNo=st.student_admissionno_var and st.classdetail_id_int=? and st.classsection_id_int=? and fc.accYear=? and fc.termcode=?";
	
	public static final String GET_TOT_SECTIONS = "select classsection_name_var,classsection_id_int from campus_classsection where classdetail_id_int=?";
	
	
	

	//Class Teacher Mapped List
	
	public static final String CLASS_TEACHER_MAPPED_LIST = "select cls.classdetail_id_int,cls.locationId,cls.classdetails_name_var,sec.classsection_id_int,sec.classsection_name_var ,(case when map.SectionCode=sec.classsection_id_int then (select concat(FirstName,' ',LastName)as teaname from campus_teachers where TeacherID=map.TeacherCode) else '-' end)teachername , (case when map.SectionCode=sec.classsection_id_int then (select TeacherID from  campus_teachers where TeacherID=map.TeacherCode) else '-' end)teacherid from campus_classdetail cls,campus_classsection sec left outer join  campus_classteacher map on  map.SectionCode=sec.classsection_id_int  where cls.classdetail_id_int=sec.classdetail_id_int order by LENGTH(cls.classdetail_id_int),cls.classdetail_id_int,sec.classsection_name_var";

	public static final String SEARCH_CLASS_TEACHER = "select distinct cls.classdetail_id_int,cls.classdetails_name_var,sec.classsection_id_int,sec.classsection_name_var ,(case when map.SectionCode=sec.classsection_id_int then (select concat(FirstName,' ',LastName)as teaname from campus_teachers where TeacherID=map.TeacherCode) else '-' end)teachername ,(case when map.SectionCode=sec.classsection_id_int then (select TeacherID from  campus_teachers where TeacherID=map.TeacherCode) else '-' end)teacherid from campus_teachers ct left outer join  campus_classteacher map on ct.TeacherID=map.TeacherCode,campus_classdetail cls,campus_classsection sec where cls.classdetail_id_int=sec.classdetail_id_int and map.TeacherCode =ct.TeacherID and (ct.FirstName like ? or ct.LastName like ? or cls.classdetails_name_var like ? or sec.classsection_name_var like ? )order by cls.classdetails_name_var and sec.classsection_name_var and ct.FirstName and ct.LastName";
	
	
	// Fee paid Status Report written by seshu
	
/*	public static final String GET_FEE_STATUS_REPORT = "select cd.classdetails_name_var,cls.classsection_name_var,cls.classsection_id_int,st.student_admissionno_var,concat(st.student_fname_var,' ',st.student_lname_var) studentname,fc.totalamount,fc.actualamount,fc.conc_amount,fc.paidDate,case when st.student_admissionno_var=fc.admissionNo then 'Paid' else 'NotPaid' end as feestatus from campus_classdetail cd,campus_classsection cls,campus_student st left outer join campus_fee_collection fc on st.student_admissionno_var=fc.admissionNo and fc.termcode=? and fc.accYear=? where st.classdetail_id_int=cd.classdetail_id_int and st.classdetail_id_int=? and st.classsection_id_int=cls.classsection_id_int and st.classsection_id_int like ? and st.student_status_var='active' order by st.classsection_id_int,studentname";
*/	
/*	public static final String GET_CLASS_FEE_AMOUNT = "select sum(fstd.feeAmount)ActualAmount from campus_fee_setup fst, campus_fee_setupdetails fstd where fstd.feeSettingCode=fst.feeSettingcode and  fst.ClassCode=? and fst.AccyearCode=? and fst.Termcode=?";
*/	
	/*public static final String GET_STAGE_FEE_AMOUNT = "select sum(fstgd.feeAmount)transportfee from campus_fee_stagesetup fstg,campus_fee_stagesetupdetails fstgd where fstg.ClassCode=? and fstg.stageSettingCode=fstgd.stageSettingCode and fstg.AccyearCode=? and fstg.Termcode=?";
	*/
	public static final String GET_FEEPAID_STATUS_REPORT = "select cd.classdetails_name_var,cls.classsection_name_var,cls.classsection_id_int,st.student_admissionno_var,concat(st.student_fname_var,' ',st.student_lname_var) studentname,fc.totalamount,fc.actualamount,fc.conc_amount,fc.paidDate from campus_classdetail cd,campus_classsection cls,campus_student st,campus_fee_collection fc  where st.classdetail_id_int=cd.classdetail_id_int and st.classdetail_id_int=? and st.classsection_id_int=cls.classsection_id_int and st.classsection_id_int like ? and st.student_status_var='active' and st.student_admissionno_var=fc.admissionNo and fc.termcode=? and fc.accYear=? order by st.classsection_id_int,studentname";
	
	public static final String GET_FEENOTPAID_STATUS_REPORT = "select cd.classdetails_name_var,cls.classsection_name_var,cls.classsection_id_int,st.student_admissionno_var,concat(st.student_fname_var,' ',st.student_lname_var) studentname from campus_classdetail cd,campus_classsection cls,campus_student st,campus_fee_collection fc where st.classdetail_id_int=cd.classdetail_id_int and st.classdetail_id_int=? and st.classsection_id_int=cls.classsection_id_int and st.classsection_id_int like ? and st.student_status_var='active' and st.student_admissionno_var!=fc.admissionNo and fc.termcode=? and fc.accYear=? order by st.classsection_id_int,studentname";
	
	//pay certificate
	public static final String GET_STUDENTCOUNT ="select count(*) studentcount from campus_student where classdetail_id_int=? and classsection_id_int=? and student_status_var='active'";
	public static final String GET_TEACHER_PAYCERTIFICATE = "select tea.TeacherID,concat(tea.FirstName,' ',LastName) as teachername,des.designationName,mn.Net_Salary,mn.Leave_Deductions,mn.Total_Deductions,mn.Employee_Pf,sa.GrossSalary,sa.CTC from campus_teachers tea,campus_designation des,campus_month_payroll mn,campus_staff_salarydetails sa where tea.designation=des.DesignationCode and tea.TeacherID=mn.Emp_Id and tea.TeacherID=sa.TeacherID and mn.Emp_Id=? and mn.Month=? and mn.Year=?";
	public static final String GET_CLASS_SECTION = "select cls.classdetail_id_int,cls.classdetails_name_var,sec.classsection_id_int,sec.classsection_name_var from campus_classdetail cls,campus_classsection sec where cls.classdetail_id_int=? and sec.classsection_id_int=?";
	public static final String GET_CLASS_SECTION_TEACHER = "select cls.classdetail_id_int,cls.classdetails_name_var,sec.classsection_id_int,sec.classsection_name_var, tea.TeacherID,concat(tea.FirstName,' ',LastName)as teachername from campus_classdetail cls,campus_classsection sec,campus_teachers tea where cls.classdetail_id_int=? and sec.classsection_id_int=? and tea.TeacherID=?";
	public static final String UPDATE_CLASS_TEACHER = "update campus_classteacher set TeacherCode=? where ClassCode=? and SectionCode=?";
	public static final String VALIDATE_CLASS_TEACHER = "select count(*) count from campus_classteacher where ClassCode=? and SectionCode=? and TeacherCode=?";
	public static final String SAVE_CLASS_TEACHER = "insert into campus_classteacher(CTCode,ClassCode,SectionCode,TeacherCode,CreateTime,CreateUser,locationId) values(?,?,?,?,?,?,?)";
	//Online Fee Receipt
	
	public static final String GET_PARENT_STUDENT_DETAILS = "select stu.student_id_int,concat(stu.student_fname_var,' ',student_lname_var) as studentname from campus_student stu,campus_parentchildrelation par where par.stu_addmissionNo=stu.student_id_int and stu.classsection_id_int=? and par.parentid=?";
/*	public static final String GET_FEE_RECEIPT_LIST = "select fc.feeAmount,fee.admissionNo,fee.paidDate,stu.student_id_int,concat(stu.student_fname_var,' ',student_lname_var)as studentname,cls.classdetails_name_var,sec.classsection_name_var,fee.totalamount,trm.termname,fn.FeeName from campus_fee_collection fee,campus_student stu,campus_classdetail cls,campus_classsection sec,campus_fee_termdetails trm ,campus_fee_master fn,campus_fee_collectiondetails fc where fee.admissionNo=stu.student_admissionno_var and  stu.classdetail_id_int=cls.classdetail_id_int and stu.classsection_id_int=sec.classsection_id_int and fc.feeCode=fn.FeeCode and fee.feeCollectionCode=fc.feeCollectionCode and fee.termcode=trm.termid and fee.accYear=? and stu.student_id_int=?";
*/
/*	public static final String GET_FEE_RECEIPT_LIST = "select stu.student_id_int,stu.student_admissionno_var,concat(stu.student_fname_var,' ',student_lname_var)as studentname ,cls.classdetails_name_var,sec.classsection_name_var ,acy.acadamic_year,fee.payment_date,fee.paid_amount,fee.total_amount,fee.due_amount from campus_student stu join campus_classdetail cls on cls.classdetail_id_int=stu.classdetail_id_int join campus_classsection sec on sec.classsection_id_int=stu.classsection_id_int join campus_acadamicyear acy on acy.acadamic_id = stu.fms_acadamicyear_id_int join campus_payment_collection fee on fee.student_id = stu.student_id_int where fee.academicyear_id=? and stu.student_id_int=? ";
*/
	//Student Marks Details Report
		
		public static final String GET_STUDENT_MARKS="select st.student_admissionno_var,concat(st.student_fname_var,' ',st.student_lname_var) studentName,ex.examname,sub.subjectName,mu.maximum_marks,mu.required_marks,m.scoredmarks from campus_subject sub,campus_student st,campus_marks_upload mu,campus_marks m,campus_examination ex where mu.examid=ex.examid and mu.subid=sub.subjectID and mu.marks_upload_id=m.marks_upload_id and m.admissionno=st.student_id_int and mu.examid=? and mu.classid=? and mu.sectionid=? and m.admissionno like ? and st.fms_acadamicyear_id_int=?";

	//Student Marks Details Report
		
				public static final String GET_CLASS_WISE_EXAM_DETAILS="select ex.examname,sub.subjectName,mu.maximum_marks,mu.required_marks,ext.examdate,ext.examtime,ext.endtime from campus_examination ex,campus_subject sub,campus_examination_timetable ext left outer join campus_marks_upload mu on mu.examid=ext.examinationid where ex.examid=ext.examinationid and ext.classid=? and ex.acadamicyear=? and sub.subjectID=ext.subjectid";

				public static final String GET_INACTIVE_STUDENTSiNFORMATION = "select student_admissionno_var,concat(student_fname_var,' ',student_lname_var) as studentname,student_age_int,student_doj_var,FatherName,mobileno,student_mothername_var,student_mothermobileno_var from campus_student st,campus_parents p,campus_parentchildrelation pc where pc.stu_addmissionNo=st.student_id_int and pc.parentid=p.ParentID and st.student_status_var ='inactive'  and fms_acadamicyear_id_int=? and fms_classstream_id_int=? and classdetail_id_int=? and classsection_id_int=?"; 
				

				public static final String GET_INACTIVE_STUDENTS_FEE_INFORMATION = "select st.student_admissionno_var,concat(st.student_fname_var,' ',st.student_lname_var)as studentname, concat(cls.classdetails_name_var,'-',sec.classsection_name_var)as ClassName,pt.FatherName,pt.mobileno,pt.student_mothername_var,pt.student_mothermobileno_var, pt.student_gaurdianname_var,pt.student_gardian_mobileno,cfc.totalamount,cfc.is_paid,cfc.paidDate,trm.termname from campus_parents pt join campus_parentchildrelation prc on prc.parentid = pt.ParentID join campus_student st on st.student_id_int = prc.stu_addmissionNo join campus_classdetail cls on cls.classdetail_id_int = st.classdetail_id_int join campus_classsection sec on sec.classsection_id_int = st.classsection_id_int join campus_fee_collection cfc on cfc.admissionNo = st.student_admissionno_var join campus_fee_termdetails trm on trm.termid = cfc.termcode where student_status_var = 'inactive' and st.fms_acadamicyear_id_int = ? order by st.student_admissionno_var asc " ;
				public static final String GET_ONE_SELECTED_ITEMS = "select acc.acadamic_year from campus_acadamicyear acc where acc.acadamic_id=? ";
				public static final String GET_FEE_RECEIPT_LIST = "select  fcd.concessionPercent,trm.termname,st.student_id_int,st.student_admissionno_var ,fc.admissionNo,fcd.feeAmount, fcd.finalFeeAmtcollected,fcd.outstandingfee,fcd.feepaiddate,fcm.FeeName,fcd.consfeeAmount, concat(st.student_fname_var,' ',student_lname_var)as studentname,cls.classdetails_name_var,sec.classsection_name_var ,acy.acadamic_year from campus_student st,campus_fee_reciept fcd,campus_fee_collection fc,campus_fee_termdetails trm,campus_fee_master fcm , campus_classsection sec,campus_classdetail cls ,campus_acadamicyear acy where fc.admissionNo=st.student_id_int and fcd.feeCollectionCode=fc.feeCollectionCode and  fcm.FeeCode=fcd.feeCode and st.classdetail_id_int=cls.classdetail_id_int and acy.acadamic_id = st.fms_acadamicyear_id_int and st.classsection_id_int=sec.classsection_id_int and fc.termcode=trm.termid  and fc.accYear=? and st.student_id_int=? order by feepaiddate";
				
				public static final String GET_CLASS_FEE_AMOUNT = "select sum(fstd.feeAmount)ActualAmount from campus_fee_setup fst, campus_fee_setupdetails fstd where fstd.feeSettingCode=fst.feeSettingcode and  fst.ClassCode=? and fst.AccyearCode=? and fst.Termcode=?";
				public static final String GET_STAGE_FEE_AMOUNT = "select sum(fstgd.feeAmount)transportfee from campus_fee_stagesetup fstg,campus_fee_stagesetupdetails fstgd where fstg.ClassCode=? and fstg.stageSettingCode=fstgd.stageSettingCode and fstg.AccyearCode=? and fstg.Termcode=?";
				public static final String GET_FEE_STATUS_REPORT = "select st.student_admissionno_var,st.student_id_int,concat(st.student_fname_var,' ',st.student_lname_var) studentname,fc.is_paid,cls.classdetails_name_var, sec.classsection_name_var,fc.totalamount,fc.actualamount,fc.balance_amount,fc.amount_paid,st.classsection_id_int  from campus_student st join campus_classdetail cls on cls.classdetail_id_int = st.classdetail_id_int join campus_classsection sec on sec.classsection_id_int = st.classsection_id_int join campus_fee_collection fc on fc.admissionNo = st.student_id_int where fc.termcode=? and fc.accYear=? and  st.classdetail_id_int=? and st.classsection_id_int like ? and st.student_status_var='active' and st.student_id_int like ?  order by  studentname";
				public static final String GET_SINGLE_FEE_STATUS_REPORT = "SELECT cfc.*,cs.student_fname_var,cs.student_lname_var FROM `campus_fee_collection` cfc LEFT JOIN `campus_student` cs ON cfc.admissionNo=cs.student_id_int WHERE cfc.admissionNo=?";
				public static final String GET_SINGLE_FEE_STATUS_REPORT_DAYWISE = "SELECT cfcdd.*,cfm.FeeName FROM `campus_fee_collectiondetails_daywise` cfcdd LEFT JOIN `campus_fee_master` cfm ON cfcdd.feeCode=cfm.FeeCode WHERE cfcdd.feeCollectionCode=?";

	// Student ID Cards
				public static final String GET_STUDENT_ID_DETAILS="SELECT stu.student_id_int,CONCAT(stu.student_fname_var,'  ',stu.student_lname_var) AS studentName,stu.student_admissionno_var,stu.student_imgurl_var,cl.classdetails_name_var,sec.classsection_name_var,ccls.classstream_name_var ,acc.endDate,cpara.address,cpara.mobileno FROM campus_student stu,campus_classsection sec,campus_classdetail cl,campus_classstream ccls,campus_acadamicyear acc,campus_student_classdetails cstu ,campus_parentchildrelation cpch,campus_parents cpara WHERE stu.student_id_int=cstu.student_id_int AND stu.student_id_int=cpch.stu_addmissionNo AND cpara.ParentID=cpch.parentid  AND cl.classdetail_id_int=cstu.classdetail_id_int AND acc.acadamic_id = cstu.fms_acadamicyear_id_int AND sec.classsection_id_int=cstu.classsection_id_int  AND cstu.fms_classstream_id_int=ccls.classstream_id_int AND stu.student_id_int like ? and cstu.fms_acadamicyear_id_int  like ? and cstu.classdetail_id_int like ? and cstu.classsection_id_int like ?";
				public static final String GET_STUDENT_ID_SEARCH="SELECT stu.student_id_int,CONCAT(stu.student_fname_var,'  ',stu.student_lname_var) AS studentName,stu.student_admissionno_var,stu.student_imgurl_var,cl.classdetails_name_var,sec.classsection_name_var,ccls.classstream_name_var ,acc.endDate FROM campus_student stu,campus_student_classdetails cstu,campus_classsection sec,campus_classdetail cl,campus_classstream ccls,campus_acadamicyear acc WHERE stu.student_id_int=cstu.student_id_int and cl.classdetail_id_int=cstu.classdetail_id_int AND acc.acadamic_id =cstu.fms_acadamicyear_id_int AND sec.classsection_id_int=cstu.classsection_id_int AND cstu.fms_classstream_id_int=ccls.classstream_id_int AND cstu.fms_acadamicyear_id_int like ? AND cstu.classdetail_id_int like ? AND cstu.classsection_id_int like ?";
				public static final String GET_STUDENT_ID_MULTIPLE_DETAILS="select DISTINCT cl.Location_Name,cl.Location_Address,cl.Location_Phone,acc.endDate,st.fms_acadamicyear_id_int,cl.Location_Id,cpcr.parentid,par.FatherName,par.mobileno,par.student_mothername_var,par.student_mothermobileno_var,CASE WHEN par.PresentAddress='' THEN par.address ELSE par.PresentAddress END address,par.student_gaurdianname_var,par.student_gardian_mobileno,st.student_id_int,cstd.student_rollno,st.student_admissionno_var,CONCAT(st.student_fname_var,'  ',st.student_lname_var) AS studentName,cstd.student_imgurl_var,acc.acadamic_year,cd.classdetails_name_var,sec.classsection_name_var,cstd.student_status,cl.Location_Name,cstd.secondlanguage,cstd.thirdlanguage,chs.housename,cstd.fms_classstream_id_int,st.student_dob_var,st.adharNo,st.student_bloodgroup_var from campus_student st join campus_student_classdetails cstd on st.student_id_int=cstd.student_id_int join campus_student_transportdetails stt on st.student_id_int=stt.student_id_int join campus_parentchildrelation cpcr on cpcr.stu_addmissionNo=st.student_id_int join campus_parents par on cpcr.parentid=par.ParentID join campus_classdetail cd on cd.classdetail_id_int=cstd.classdetail_id_int join campus_classsection sec on sec.classsection_id_int=cstd.classsection_id_int join campus_acadamicyear acc on acc.acadamic_id=cstd.fms_acadamicyear_id_int join campus_location cl on cstd.locationId=cl.Location_Id left join campus_student_house cgh on cgh.student_id=st.student_id_int left join campus_house_settings chs on chs.house_id=cstd.student_house where cstd.student_id_int=? and cstd.fms_acadamicyear_id_int=? and cstd.locationId=?";
				public static final String GET_STAFF_ID_MULTIPLE_DETAILS="SELECT  CONCAT(ct.FirstName,' ',ct.LastName)AS teacherName,ct.Abbreviative_Id,CASE WHEN ct.imagePath IS NULL THEN 'noImage' ELSE ct.imagePath END imagePath ,ct.registerId,cd.designationName,cd.designationCode,cdp.DEPT_NAME,cdp.DEPT_ID,ct.mobileNo,ct.presentAddress,cl.Location_Name,cl.Location_Address,cl.Location_Phone FROM campus_designation cd ,campus_location cl,campus_department cdp,campus_teachers ct WHERE ct.department=cdp.DEPT_ID AND ct.designation=cd.DesignationCode AND ct.Loc_ID=cl.Location_Id AND ct.TeacherID LIKE ? AND cl.Location_Id LIKE ? ORDER BY CAST(SUBSTR(cl.Location_Id,4)AS UNSIGNED),CAST(SUBSTR(cd.DesignationCode,4)AS UNSIGNED)"; 

				
				public static final String GET_TEMP_ID="select schl_adm_id from campus_temporary_admisssion_details order by createdTime desc  limit 1";
				public static final String GET_THIRD_ID="select third_admid from campus_third_admission_details order by createdTime desc  limit 1";
	// Location details			
				public static final String GETLOCATION = "select Location_Id,Location_Name from campus_location";
				public static final String GETSTUDENTSDOBWISE = "select distinct stu.student_admissionno_var,case when cscd.student_rollno is null then '-' else cscd.student_rollno end student_rollno,ccd.classdetails_name_var,ccs.classsection_name_var,concat(stu.student_fname_var,' ',stu.student_lname_var)as studentName,stu.student_dob_var from campus_student stu left join campus_student_classdetails cscd on cscd.student_id_int=stu.student_id_int left join campus_classdetail ccd on ccd.classdetail_id_int=cscd.classdetail_id_int left join campus_classsection ccs on ccs.classsection_id_int=cscd.classsection_id_int where cscd.fms_acadamicyear_id_int like ? and cscd.locationId like ? and cscd.classdetail_id_int like ? and cscd.classsection_id_int like ? order by cscd.student_rollno";
				public static final String GETSTUDENTS_FATHER_OCC_WISE = "select distinct stu.student_admissionno_var,case when cscd.student_rollno is null then '-' else cscd.student_rollno end student_rollno,concat(stu.student_fname_var,' ',stu.student_lname_var)as studentName,case when cp.FatherName is null then '-' else cp.FatherName end FatherName,case when co.occupation is null then '-' else co.occupation end occupation from campus_student stu left join campus_student_classdetails cscd on cscd.student_id_int=stu.student_id_int left join campus_parentchildrelation cpcr on cpcr.stu_addmissionNo=stu.student_id_int left join campus_parents cp on cp.ParentID=cpcr.parentid left join campus_occupation co on co.occupationId=cp.student_father_occupation where cscd.fms_acadamicyear_id_int like ? and cscd.locationId like ? and cscd.classdetail_id_int like ? and cscd.classsection_id_int like ? order by cscd.student_rollno";
				public static final String GETSTUDENTS_MOTHER_OCC_WISE = "select distinct stu.student_admissionno_var,case when cscd.student_rollno is null then '-' else cscd.student_rollno end student_rollno,concat(stu.student_fname_var,' ',stu.student_lname_var)as studentName,case when cp.student_mothername_var is null then '-' else cp.student_mothername_var end student_mothername_var,case when co.occupation is null then '-' else co.occupation end occupation from campus_student stu left join campus_student_classdetails cscd on cscd.student_id_int=stu.student_id_int left join campus_parentchildrelation cpcr on cpcr.stu_addmissionNo=stu.student_id_int left join campus_parents cp on cp.ParentID=cpcr.parentid left join campus_occupation co on co.occupationId=cp.student_mother_occupation where cscd.fms_acadamicyear_id_int like ? and cscd.locationId like ? and cscd.classdetail_id_int like ? and cscd.classsection_id_int like ? order by cscd.student_rollno";
				public static final String GETSTUDENTSRELIGIONWISE = "select stu.student_admissionno_var,case when cscd.student_rollno is null then '-' else cscd.student_rollno end student_rollno,concat(stu.student_fname_var,' ',stu.student_lname_var)as studentName,cr.religion,cc.caste from campus_student stu left join campus_religion cr on cr.religionId=stu.student_religion_var left join campus_caste cc on cc.casteId=stu.student_caste left join campus_student_classdetails cscd on cscd.student_id_int=stu.student_id_int where cscd.fms_acadamicyear_id_int like ? and cscd.locationId like ? and cscd.classdetail_id_int like ? and cscd.classsection_id_int like ? order by cscd.student_rollno";
				public static final String GETSTUDENTSCATEGORYWISE = "select stu.student_admissionno_var,case when cscd.student_rollno is null then '-' else cscd.student_rollno end student_rollno,concat(stu.student_fname_var,' ',stu.student_lname_var)as studentName,cr.religion,cc.caste,ccc.casteCategory from campus_student stu left join campus_religion cr on cr.religionId=stu.student_religion_var left join campus_caste cc on cc.casteId=stu.student_caste left join campus_caste_category ccc on ccc.castCatId=stu.casteCategory left join campus_student_classdetails cscd on cscd.student_id_int=stu.student_id_int where cscd.fms_acadamicyear_id_int like ? and cscd.locationId like ? and cscd.classdetail_id_int like ? and cscd.classsection_id_int like ? order by cscd.student_rollno";
				public static final String GETSTUDENTSSTANDARDLIST = "select stu.student_admissionno_var,case when cscd.student_rollno is null then '-' else cscd.student_rollno end student_rollno,concat(stu.student_fname_var,' ',stu.student_lname_var) as studentName,stu.student_gender_var,cr.religion,cc.caste,ccc.casteCategory,stu.student_dob_var from campus_student stu left join campus_religion cr on cr.religionId=stu.student_religion_var left join campus_caste cc on cc.casteId=stu.student_caste left join campus_caste_category ccc on ccc.castCatId=stu.casteCategory left join campus_student_classdetails cscd on cscd.student_id_int=stu.student_id_int where cscd.fms_acadamicyear_id_int like ? and cscd.locationId like ? and cscd.classdetail_id_int like ? and cscd.classsection_id_int like ? order by cscd.student_rollno";
	
   // Class Details
				public static final String GETCLASSDETAILS = "select classdetail_id_int,classdetails_name_var from campus_classdetail order by length(classdetail_id_int),classdetail_id_int; ";
				public static final String GET_BUS_STUDENT_ID_DETAILS = "SELECT DISTINCT cloc.Location_Name,stu.student_id_int,CONCAT(stu.student_fname_var,'  ',stu.student_lname_var) AS studentName,stu.student_admissionno_var,CASE WHEN cstd.student_imgurl_var IS NULL THEN 'FIles/STUDENTIMAGES/noImage.png' ELSE cstd.student_imgurl_var END student_imgurl_var,cl.classdetails_name_var,sec.classsection_name_var,ccls.classstream_name_var ,acc.endDate,cpara.address,cpara.mobileno,tr.Route_No,csta.stage_name,cdrop.stage_name drop_point FROM campus_student stu,campus_classsection sec,campus_classdetail cl,campus_classstream ccls,campus_acadamicyear acc ,campus_parentchildrelation cpch,campus_parents cpara,transport_route tr,campus_fee_stage csta,campus_student_classdetails cstd,campus_location cloc,campus_student_route_stage_mapping cstr,campus_fee_stage cdrop WHERE  stu.student_id_int=cstd.student_id_int AND stu.student_id_int=cstr.mapped_id AND cstr.stage_id=csta.stage_id AND cstr.drop_point=cdrop.stage_id AND cstr.route_id=tr.RouteCode AND stu.student_id_int=cpch.stu_addmissionNo AND cpara.ParentID=cpch.parentid  AND cl.classdetail_id_int=cstd.classdetail_id_int AND cl.locationId=cstd.locationId AND cloc.Location_Id=cstd.locationId AND acc.acadamic_id = cstd.fms_acadamicyear_id_int AND sec.classsection_id_int=cstd.classsection_id_int  AND cstd.fms_classstream_id_int=ccls.classstream_id_int  AND cstd.locationId = ? AND cstd.fms_acadamicyear_id_int =? AND cstd.fms_classstream_id_int=? AND stu.student_id_int= ?";
				public static final String GETSTUDENTSPARENTWISE = "select distinct stu.student_admissionno_var,case when cscd.student_rollno is null then '-' else cscd.student_rollno end student_rollno,concat(stu.student_fname_var,' ',stu.student_lname_var)as studentName,case when cp.FatherName is null then '-' else cp.FatherName end FatherName,cp.mobileno,case when cp.student_mothername_var is null then '-' else cp.student_mothername_var end student_mothername_var,cp.student_mothermobileno_var,cp.address from campus_student stu left join campus_parentchildrelation cpcr on cpcr.stu_addmissionNo=stu.student_id_int left join campus_parents cp on cp.ParentID=cpcr.parentid left join campus_student_classdetails cscd on cscd.student_id_int=stu.student_id_int where cscd.fms_acadamicyear_id_int like ? and cscd.locationId like ? and cscd.classdetail_id_int like ? and cscd.classsection_id_int like ? order by cscd.student_rollno";
				public static final String GETSTUDENTSLIST = "select stu.student_admissionno_var,case when cscd.student_rollno is null then '-' else cscd.student_rollno end student_rollno,concat(stu.student_fname_var,' ',stu.student_lname_var) as studentName from campus_student stu left join campus_student_classdetails cscd on cscd.student_id_int=stu.student_id_int where cscd.fms_acadamicyear_id_int like ? and cscd.locationId like ? and cscd.classdetail_id_int like ? and cscd.classsection_id_int like ? order by LENGTH(cscd.student_rollno),studentName";
				public static final String STUDENTSCONTACTDETAILS = "select stu.student_admissionno_var,case when cscd.student_rollno is null then '-' else cscd.student_rollno end student_rollno,concat(stu.student_fname_var,' ',stu.student_lname_var)as studentName,cp.FatherName,cp.mobileno,cp.student_mothername_var,cp.student_mothermobileno_var,cp.address from campus_student stu left join campus_parentchildrelation cpcr on cpcr.stu_addmissionNo=stu.student_id_int left join campus_parents cp on cp.ParentID=cpcr.parentid left join campus_student_classdetails cscd on cscd.student_id_int=stu.student_id_int where cscd.fms_acadamicyear_id_int like ? and cscd.locationId like ? and cscd.classdetail_id_int like ? and cscd.classsection_id_int like ? order by cscd.student_rollno";
				public static final String GETSTUDENTSDEPARTMENTLIST = "select stu.student_admissionno_var,concat(stu.student_fname_var,' ',stu.student_lname_var)as studentName,ccd.classdetails_name_var,ccs.classsection_name_var,ccsp.Specialization_name from campus_student stu join campus_student_classdetails cscd on cscd.student_id_int=stu.student_id_int join campus_classdetail ccd on ccd.classdetail_id_int=cscd.classdetail_id_int join campus_classsection ccs on ccs.classsection_id_int=cscd.classsection_id_int join campus_class_specialization ccsp on ccsp.Specialization_Id=cscd.specilization where cscd.fms_acadamicyear_id_int like ? and cscd.locationId like ? and cscd.classdetail_id_int like ? and cscd.classsection_id_int like ? order by stu.student_admissionno_var";
				public static final String GETSTUDENTSBUSROUTEWISE = "select stu.student_admissionno_var,concat(stu.student_fname_var,' ',stu.student_lname_var)as studentName,ccd.classdetails_name_var,ccs.classsection_name_var,cfs.stage_name,cfs.amount from campus_student stu join campus_student_classdetails cscd on cscd.student_id_int=stu.student_id_int join campus_classdetail ccd on ccd.classdetail_id_int=cscd.classdetail_id_int join campus_classsection ccs on ccs.classsection_id_int=cscd.classsection_id_int join campus_student_transportdetails cstd on cstd.student_id_int=stu.student_id_int join campus_fee_stage cfs on cfs.stage_id=cstd.StageId where cscd.fms_acadamicyear_id_int like ? and cscd.locationId like ? and cscd.classdetail_id_int like ? and cscd.classsection_id_int like ? order by cfs.stage_name";
				public static final String GETSTUDENTSOPTIONALSUBJECT = "select distinct stu.student_id_int,stu.student_admissionno_var,concat(stu.student_fname_var,' ',stu.student_lname_var)as studentName,ccd.classdetails_name_var,ccs.classsection_name_var,case when cscd.secondlanguage is null then '-' else cscd.secondlanguage end secondlanguage,case when cscd.thirdlanguage is null then '-' else cscd.thirdlanguage end thirdlanguage  from campus_student stu left join campus_student_classdetails cscd on cscd.student_id_int=stu.student_id_int left join campus_classdetail ccd on ccd.classdetail_id_int=cscd.classdetail_id_int left join campus_classsection ccs on ccs.classsection_id_int=cscd.classsection_id_int where cscd.fms_acadamicyear_id_int like ? and cscd.locationId like ? and cscd.classdetail_id_int like ? and cscd.classsection_id_int like ? order by stu.student_admissionno_var,ccs.classsection_name_var";
				public static final String GETSTUDENTSWITHPHONENUMBER = "select stu.student_admissionno_var,case when cscd.student_rollno is null then '-' else cscd.student_rollno end student_rollno,cscd.student_rollno,concat(stu.student_fname_var,' ',stu.student_lname_var)as studentName,case when cp.FatherName is null then '-' else cp.FatherName end FatherName,cp.mobileno,case when cp.student_mothername_var is null then '-' else cp.student_mothername_var end student_mothername_var,cp.student_mothermobileno_var,cp.student_gaurdianname_var,cp.student_gardian_mobileno from campus_student stu left join campus_student_classdetails cscd on cscd.student_id_int=stu.student_id_int left join campus_parentchildrelation cpcr on cpcr.stu_addmissionNo=stu.student_id_int left join campus_parents cp on cp.ParentID=cpcr.parentid where cscd.fms_acadamicyear_id_int like ? and cscd.locationId like ? and cscd.classdetail_id_int like ? and cscd.classsection_id_int like ? order by cscd.student_rollno";
				public static final String GETOLDSTUDENTLIST = "";
				public static final String GETSTUDENTSSTRENGTH = "select count(sc.student_id_int)as stucount,st.student_gender_var,sc.classdetail_id_int,sc.classsection_id_int from campus_student_classdetails sc join campus_student st on sc.student_id_int = st.student_id_int where sc.fms_acadamicyear_id_int like ? and sc.locationId like ? and sc.classdetail_id_int = ? and sc.classsection_id_int = ? group by st.student_gender_var order by st.student_gender_var";
				public static final String GETSTUDENTSNEWADMISSONLIST = "select stu.student_id_int,stu.student_admissionno_var,concat(stu.student_fname_var,' ',stu.student_lname_var)as studentName,ccd.classdetails_name_var,ccs.classsection_name_var,stu.student_doj_var from campus_student stu join campus_student_classdetails cscd on cscd.student_id_int=stu.student_id_int join campus_classdetail ccd on ccd.classdetail_id_int=cscd.classdetail_id_int join campus_classsection ccs on ccs.classsection_id_int=cscd.classsection_id_int where  stu.fms_acadamicyear_id_int=cscd.fms_acadamicyear_id_int and stu.fms_acadamicyear_id_int like ? and stu.locationId like ? and (stu.tempadmissionregno not in ('NULL') and stu.tempadmissionregno not in (' ')) and cscd.classdetail_id_int like ? and cscd.classsection_id_int like ? order by ccd.classdetails_name_var,ccs.classsection_name_var";
				public static final String GETSTUDENTSPROMOTIONLIST = "select distinct stu.student_id_int,case when cscd.student_rollno is null then '-' else cscd.student_rollno end student_rollno,concat(stu.student_fname_var,' ',stu.student_lname_var)as studentName,csp.studentpromotion_status from campus_student stu join campus_student_classdetails cscd on cscd.student_id_int=stu.student_id_int join campus_student_promotion csp on (csp.student_id_int=cscd.student_id_int and csp.studentpromotion_acadamicyearfrom_var=cscd.fms_acadamicyear_id_int) where csp.studentpromotion_acadamicyearfrom_var like ? and csp.studentpromotion_fromclass_var like ? and csp.studentpromotion_fromsection_var like ? and csp.studentpromotion_status='promoted' order by cscd.student_rollno";
				public static final String GETSTUDENTSLISTGENDERWISE = "select stu.student_admissionno_var,stu.student_gender_var,case when cscd.student_rollno is null then '-' else cscd.student_rollno end student_rollno,concat(stu.student_fname_var,' ',stu.student_lname_var) as studentName from campus_student stu left join campus_student_classdetails cscd on cscd.student_id_int=stu.student_id_int where cscd.fms_acadamicyear_id_int like ? and cscd.locationId like ? and cscd.classdetail_id_int like ? and cscd.classsection_id_int like ? and stu.student_gender_var like ? order by cscd.student_rollno";
				public static final String GETSUBJECTDETAILS = "select subjectID,subjectName from campus_subject where classid=? and locationId=?";
				public static final String GETACCESSION_NO ="SELECT Accession_number FROM campus_library_stock_entry";
				public static final String GET_EXAM = "SELECT `examcode` FROM `campus_exam_timetable` WHERE `accyear_id`=? AND `loc_id`=? AND `class_id`=? AND `section_id`=?";
				public static final String GET_DEP_EXAM = "SELECT COUNT(*) FROM`campus_exam_dependency` WHERE `Exam_code`=?";
				public static final String DEPENDENT_EXAM = "SELECT * FROM `campus_exam_dependency` WHERE `Exam_code`=?";
				public static final String EXAM_NAME = "SELECT ce.examname,SUM(stm.`scored_marks`) AS scored_marks,SUM(stm.`notebook_marks`) notebook_marks,SUM(stm.`subject_enrich_marks`) subject_enrich_marks,SUM(stm.`periodic_test`) periodic_test,SUM(stm.`total_marks`) AS totalmarks,SUM(stm.`max_periodic_marks`) AS max_periodic_marks,SUM(stm.`max_notebook_marks`) max_notebook_marks,SUM(stm.`max_subjenrich_marks`) max_subjenrich_marks FROM campus_examination ce LEFT JOIN campus_studentwise_mark_details stm ON stm.`exam_id`=ce.examid LEFT JOIN `campus_subject` sub ON sub.`subjectID`= stm.`sub_id` WHERE ce.examid=? AND stm.`stu_id`=? AND sub.`classid`=?";
				public static final String DEPENDENT_EXAM_SCORE = "SELECT cm.`ScoredMarks`,cm.`TotalMarks`,ce.`examname` FROM `campus_marks` cm JOIN `campus_examination` ce ON ce.`examid`=cm.`Exam`WHERE cm.`StudentId`=? AND cm.`Exam`=? AND cm.`Accyear`=? AND cm.`Classs`=? AND cm.`LocationId`=?";



				public static final String GET_FEE_COLLECTION_REPORT = "SELECT cft.termname,fc.paidDate,fc.chln_no,CONCAT(cd.classdetails_name_var, ' ',cs.classsection_name_var) AS class, CONCAT(st.student_fname_var,' ',st.student_lname_var)AS student ,pr.address,fc.paymentMode,fc.amount_paid FROM campus_student st JOIN campus_student_classdetails csc ON csc.student_id_int = st.student_id_int JOIN campus_parentchildrelation par ON par.stu_addmissionNo = csc.student_id_int JOIN  campus_parents pr ON pr.parentid = par.ParentID JOIN campus_classdetail cd ON cd.classdetail_id_int=csc.classdetail_id_int AND cd.locationId = csc.locationId JOIN campus_classsection cs ON cs.classsection_id_int=csc.classsection_id_int AND cs.locationId = csc.locationId JOIN campus_fee_collection fc ON fc.admissionNo = csc.student_id_int join campus_fee_termdetails cft on cft.termid=fc.termcode where csc.locationId like ? and csc.fms_acadamicyear_id_int like ? AND fc.termcode like ? order by fc.chln_no and cd.classdetails_name_var and cs.classsection_name_var and st.student_fname_var and st.student_lname_var";


				public static final String GET_FEE_COLLECTION_CLASS_REPORT = "SELECT cft.termname,fc.paidDate,fc.chln_no,CONCAT(cd.classdetails_name_var, ' ',cs.classsection_name_var) AS class, CONCAT(st.student_fname_var,' ',st.student_lname_var)AS student ,pr.address,fc.paymentMode,fc.amount_paid FROM campus_student st JOIN campus_student_classdetails csc ON csc.student_id_int = st.student_id_int JOIN campus_parentchildrelation par ON par.stu_addmissionNo = csc.student_id_int JOIN  campus_parents pr ON pr.parentid = par.ParentID JOIN campus_classdetail cd ON cd.classdetail_id_int=csc.classdetail_id_int AND cd.locationId = csc.locationId JOIN campus_classsection cs ON cs.classsection_id_int=csc.classsection_id_int AND cs.locationId = csc.locationId JOIN campus_fee_collection fc ON fc.admissionNo = csc.student_id_int join campus_fee_termdetails cft on cft.termid=fc.termcode where csc.locationId like ? and csc.fms_acadamicyear_id_int like ? and cd.classdetail_id_int like ? AND fc.termcode like ? order by fc.chln_no and cd.classdetails_name_var and cs.classsection_name_var and st.student_fname_var and st.student_lname_var";


				public static final String GET_FEE_COLLECTION_SECTION_REPORT = "SELECT cft.termname,fc.paidDate,fc.chln_no,CONCAT(cd.classdetails_name_var, ' ',cs.classsection_name_var) AS class, CONCAT(st.student_fname_var,' ',st.student_lname_var)AS student ,pr.address,fc.paymentMode,fc.amount_paid FROM campus_student st JOIN campus_student_classdetails csc ON csc.student_id_int = st.student_id_int JOIN campus_parentchildrelation par ON par.stu_addmissionNo = csc.student_id_int JOIN  campus_parents pr ON pr.parentid = par.ParentID JOIN campus_classdetail cd ON cd.classdetail_id_int=csc.classdetail_id_int AND cd.locationId = csc.locationId JOIN campus_classsection cs ON cs.classsection_id_int=csc.classsection_id_int AND cs.locationId = csc.locationId JOIN campus_fee_collection fc ON fc.admissionNo = csc.student_id_int join campus_fee_termdetails cft on cft.termid=fc.termcode where csc.locationId like ? and csc.fms_acadamicyear_id_int like ? and cd. classdetail_id_int like ? and cs.classsection_id_int like ? AND fc.termcode like ? order by fc.chln_no and cd.classdetails_name_var and cs.classsection_name_var and st.student_fname_var and st.student_lname_var";


				public static final String GET_FEE_COLLECTION_PAYMODE_REPORT = "SELECT cft.termname,fc.paidDate,fc.chln_no,CONCAT(cd.classdetails_name_var, ' ',cs.classsection_name_var) AS class, CONCAT(st.student_fname_var,' ',st.student_lname_var)AS student ,pr.address,fc.paymentMode,fc.amount_paid FROM  campus_fee_collection fc JOIN campus_student_classdetails csc ON fc.admissionNo = csc.student_id_int AND fc.accYear=csc.fms_acadamicyear_id_int JOIN campus_student st  ON fc.admissionNo = st.student_id_int JOIN campus_parentchildrelation par ON par.stu_addmissionNo = fc.admissionNo JOIN  campus_parents pr ON pr.parentid = par.ParentID JOIN campus_classdetail cd ON cd.classdetail_id_int=csc.classdetail_id_int AND cd.locationId = csc.locationId JOIN campus_classsection cs ON cs.classsection_id_int=csc.classsection_id_int AND cs.locationId = csc.locationId  JOIN campus_fee_termdetails cft ON cft.termid=fc.termcode where csc.locationId = ? and fc.accYear = ? and cd. classdetail_id_int like ? and cs.classsection_id_int like ? and fc.paymentMode LIKE ? AND  fc.termcode like ? order by fc.paidDate,fc.chln_no,length(cd.classdetail_id_int),cd.classdetail_id_int,cs.classsection_name_var,student";
            
				//DD Reports...........
				
				public static final String GET_TERMS ="SELECT termid,termname FROM campus_fee_termdetails WHERE locationId=?";
				public static final String GET_DD_REPORT_LIST ="SELECT cfc.termcode,cfc.bank_name,cfc.paymentParticulars,cfc.dd_cheque_date,cfc.paidDate,cfc.amount_paid FROM campus_fee_collection cfc JOIN campus_fee_termdetails cft ON cft.termid=cfc.termcode  WHERE cfc.termcode LIKE ? AND cfc.accYear=? AND cft.locationId=? AND cfc.paymentMode='DD'";
				//public static final String GET_DD_REPORT_LIST ="SELECT cfc.termcode,cfc.bank_name,cfc.paymentParticulars,cfc.paidDate,cfc.amount_paid FROM campus_fee_collection cfc  WHERE cfc.termcode LIKE ? AND cfc.accYear=? AND cfc.paymentMode='DD'";

				
				public static final String get_sections_by_class_loc="select distinct classsection_id_int,classsection_name_var from campus_classsection where classdetail_id_int =? and locationId=?  order by classsection_name_var ";

				public static final String GET_FEE_COLLECTION_PAYMODE_ONLINE_REPORT = "SELECT cft.termname,fc.paidDate,fc.chln_no,CONCAT(cd.classdetails_name_var, ' ',cs.classsection_name_var) AS class, CONCAT(st.student_fname_var,' ',st.student_lname_var)AS student ,pr.address,fc.paymentMode,fc.amount_paid FROM  campus_fee_collection fc JOIN campus_student_classdetails csc ON fc.admissionNo = csc.student_id_int AND fc.accYear=csc.fms_acadamicyear_id_int JOIN campus_student st  ON fc.admissionNo = st.student_id_int JOIN campus_parentchildrelation par ON par.stu_addmissionNo = fc.admissionNo JOIN  campus_parents pr ON pr.parentid = par.ParentID JOIN campus_classdetail cd ON cd.classdetail_id_int=csc.classdetail_id_int AND cd.locationId = csc.locationId JOIN campus_classsection cs ON cs.classsection_id_int=csc.classsection_id_int AND cs.locationId = csc.locationId  JOIN campus_fee_termdetails cft ON cft.termid=fc.termcode where csc.locationId LIKE ? and fc.accYear = ? and cd. classdetail_id_int like ? and cs.classsection_id_int like ? and fc.termcode like ? and fc.paymentMode = 'Online' order by fc.chln_no and cd.classdetails_name_var and cs.classsection_name_var and st.student_fname_var and st.student_lname_var";

				public static final String GET_PARENT = "SELECT `FatherName` FROM `campus_parents` par JOIN `campus_parentchildrelation` pr ON par.`parentid` = pr.`ParentID` WHERE `stu_addmissionNo`=?";


				public static final String GET_YEAR = "SELECT `acadamic_year` FROM `campus_acadamicyear` WHERE `acadamic_id`=?";

				public static String GET_TERM="SELECT termcode FROM campus_fee_collection WHERE admissionNo=? AND accYear =?";
				public static String GET_IT_FEE="SELECT fm.FeeName,fs.feeAmount FROM campus_fee_master fm JOIN campus_fee_setupdetails fs ON fs.feecode = fm.FeeCode AND feeSettingCode IN (SELECT feeSettingCode FROM campus_fee_setup WHERE ClassCode ='CCD4' AND AccyearCode = ? AND Termcode = ? AND locationId = ?)";
				public static final String GET_STUDENT_LIST_BY_SECTION = "SELECT DISTINCT stu.student_admissionno_var,acy.acadamic_year ,CASE WHEN stu.student_lname_var IS NULL THEN stu.student_fname_var ELSE CONCAT(stu.student_fname_var,' ',stu.student_lname_var)END studentname,ccd.classdetails_name_var,ccs.classsection_name_var,loc.`Location_Name`,stm.`classstream_name_var`,ce.`examname`,ce.`examcode`,cet.`examtypename`,sub.`subjectName`,ce.`startdate`,ce.`enddate` FROM campus_student stu JOIN campus_student_classdetails csc ON stu.student_id_int=csc.student_id_int LEFT JOIN campus_classdetail ccd ON csc.classdetail_id_int=ccd.classdetail_id_int LEFT JOIN `campus_classstream` stm ON stm.`classstream_id_int`=ccd.`classstream_id_int` LEFT JOIN campus_classsection ccs ON csc.classsection_id_int=ccs.classsection_id_int LEFT JOIN `campus_subject` sub ON sub.`classid`=ccd.classdetail_id_int LEFT JOIN campus_acadamicyear acy ON csc.fms_acadamicyear_id_int=acy.acadamic_id LEFT JOIN `campus_location` loc ON loc.`Location_Id`=csc.locationId,`campus_examination` ce LEFT JOIN `campus_examtype` cet ON ce.`examtype`=cet.`examtypeid` WHERE csc.locationId =? AND csc.fms_acadamicyear_id_int=? AND csc.classdetail_id_int=? AND csc.classsection_id_int=? AND ce.`examid`=? AND sub.`subjectID`=? ORDER BY studentname";
				public static final String GET_STUDENT_LIST_BY_SECTION1 = "SELECT DISTINCT stu.student_admissionno_var,acy.acadamic_year ,CASE WHEN stu.student_lname_var IS NULL THEN stu.student_fname_var ELSE CONCAT(stu.student_fname_var,' ',stu.student_lname_var)END studentname,ccd.classdetails_name_var,ccs.classsection_name_var,loc.`Location_Name`,stm.`classstream_name_var`,ce.`examname`,ce.`examcode`,cet.`examtypename`,ce.`startdate`,ce.`enddate` FROM campus_student stu JOIN campus_student_classdetails csc ON stu.student_id_int=csc.student_id_int LEFT JOIN campus_classdetail ccd ON csc.classdetail_id_int=ccd.classdetail_id_int LEFT JOIN `campus_classstream` stm ON stm.`classstream_id_int`=ccd.`classstream_id_int` LEFT JOIN campus_classsection ccs ON csc.classsection_id_int=ccs.classsection_id_int LEFT JOIN campus_acadamicyear acy ON csc.fms_acadamicyear_id_int=acy.acadamic_id LEFT JOIN `campus_location` loc ON loc.`Location_Id`=csc.locationId,`campus_examination` ce LEFT JOIN `campus_examtype` cet ON ce.`examtype`=cet.`examtypeid` WHERE csc.locationId =? AND csc.fms_acadamicyear_id_int=? AND csc.classdetail_id_int=? AND csc.classsection_id_int=? AND ce.`examid`=? ORDER BY studentname";	
}
