package com.centris.campus.util;

public class StaffEmployementUtil {
	
	public static final String GET_STAFTSEARCH_LIST = "select TeacherID,concat(FirstName,' ',LastName) as staffName from campus_teachers where FirstName like ?";
	
	//public static final String GET_SALARY_DETAILS = "select concat(t.FirstName,' ',t.LastName) staffName,t.dateofJoining,t.TeacherID,t.registerId,d.DEPT_NAME,ss.BankAccNumber,ss.EmployeePfNo,ss.BankName,ss.IFSCCode,ss.paymentType,ss.Basic,ss.Ca,ss.HRAPercentage,ss.Hra,ss.MedicalAllowances,ss.TelephoneAllowance,ss.PerformanceIncentive,ss.FoodAllowance,ss.SpecialAllowance,ss.OtherAllowance,ss.WashingAllowance,ss.EmployerESI,ss.EmployerPf,ss.CTC,ss.GrossSalary,ss.DeduEmployerPF,ss.DeduEmployerESI,ss.IncomeTax,ss.Pt,ss.LeaveDeductions,ss.LateDeductions,ss.TDSCtc,ss.TDSStandardDeductions,ss.TDSTaxbleIncomeWithStatury,ss.TDSPT,ss.TDSPF,ss.TDSTaxbleIncome,ss.TDSTaxPayble,ss.EmployeePf,ss.EmployeeESI from campus_teachers t left outer join campus_staff_salarydetails ss on ss.TeacherID=t.TeacherID, campus_department d where d.DEPT_ID=t.department and t.TeacherID=?";
	
	public static final String GET_SALARY_DETAILS = "select concat(t.FirstName,' ',t.LastName) staffName,t.dateofJoining,t.TeacherID,t.registerId,d.DEPT_NAME,ss.BankAccNumber,ss.EmployeePfNo,ss.BankName,ss.IFSCCode,ss.paymentType,ss.Basic,ss.Hra,ss.Convenience,ss.Da,ss.PerformanceIncentive,ss.SpecialAllowance,ss.FoodAllowance,ss.SpecialAllowance,ss.OtherAllowance,ss.childEdu,ss.arrears,ss.reimbursement,ss.internetExpense,ss.driverSalary,ss.leaveEncash,ss.medicalReimbursement,ss.totalSalary,ss.pfEmployerAmount,ss.esiEmployerAmount,ss.EmployerESI,ss.EmployerPf,ss.HRAPercentage,ss.hraperamount,ss.TDSUnderChapterVIA,ss.TDSIncomeFromOther,tds.taxworkNetTax,tds.taxworkTaxableIncome,csis.incomeOtherTotal,csis.exemptTotal,csis.section80CTotal,csis.section80D80UTotal,ss.IncomeTax,ss.Pt,ss.TDSPT,ss.TDSTaxbleIncome,ss.TDSTaxPayble,ss.TDSExemption,ss.EmployeeESI,ss.EmployeePf from campus_teachers t left outer join campus_staff_salarydetails ss on ss.TeacherID=t.TeacherID left join campus_staff_tax_tds_deduction tds on tds.TeacherID=ss.TeacherID left join campus_staff_income_section csis on csis.TeacherID=ss.TeacherID, campus_department d where d.DEPT_ID=t.department and t.TeacherID=?";

	public static final String GET_SALARY_COUNT = "select count(*) from campus_staff_salarydetails where TeacherID=?";

	//public static final String INSERT_SALARY = "insert into campus_staff_salarydetails(TeacherID,BankAccNumber,EmployeePfNo,BankName,IFSCCode,paymentType,Basic,Ca,HRAPercentage,Hra,MedicalAllowances,TelephoneAllowance,PerformanceIncentive,SpecialAllowance,FoodAllowance,WashingAllowance,OtherAllowance,EmployerPf,EmployerESI,GrossSalary,CTC,DeduEmployerPF,EmployeePf,IncomeTax,Pt,DeduEmployerESI,EmployeeESI,TDSCtc,TDSStandardDeductions,TDSTaxbleIncomeWithStatury,TDSPT,TDSPF,TDSTaxbleIncome,TDSTaxPayble,CreatedBy,CreateDate,LeaveDeductions,LateDeductions) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
	public static final String INSERT_SALARY = "insert into campus_staff_salarydetails(TeacherID,BankAccNumber,EmployeePfNo,BankName,IFSCCode,paymentType,Basic,Da,Hra,Convenience,childEdu,SpecialAllowance,arrears,PerformanceIncentive,medicalReimbursement,leaveEncash,FoodAllowance,reimbursement,internetExpense,driverSalary,OtherAllowance,totalSalary,EmployerPf,EmployerESI,pfEmployerAmount,esiEmployerAmount,CreatedBy,CreateDate,HRAPercentage,hraperamount,TDSCtc,TDSStandardDeductions,TDSExemption,TDSPT,TDSTaxbleIncome,TDSTaxPayble,IncomeTax,Pt,EmployeeESI,EmployeePf,TDSUnderChapterVIA) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
	public static final String UPDATE_SALARY = "update campus_staff_salarydetails set BankAccNumber=?, EmployeePfNo=?,BankName=?,IFSCCode=?,paymentType=?,Basic=?,Da=?,Hra=?,Convenience=?,childEdu=?,SpecialAllowance=?,arrears=?,PerformanceIncentive=?,medicalReimbursement=?,leaveEncash=?,FoodAllowance=?,reimbursement=?,internetExpense=?,driverSalary=?,OtherAllowance=?,totalSalary=?,EmployerPf=?,EmployerESI=?,pfEmployerAmount=?,esiEmployerAmount=?,ModifiedBy=?,ModifiedDate=?,HRAPercentage=?,hraperamount=?,TDSCtc=?,TDSStandardDeductions=?,TDSExemption=?,TDSPT=?,TDSTaxbleIncome=?,TDSTaxPayble=?,IncomeTax=?,Pt=?,EmployeeESI=?,EmployeePf=?,TDSUnderChapterVIA=? where TeacherID=?";
	public static final String CHECK_DUPLICATE_PF_NO="select es.TeacherID from campus_staff_salarydetails es,campus_teachers e where es.TeacherID=e.TeacherID and  es.EmployeePfNo=? and es.TeacherID!=?";
	
	public static final String CHECK_BANK_ACC_NUMBER="select count(*) from campus_staff_salarydetails where BankAccNumber=? and TeacherID!=?";
	
	public static final String INSERT_SALARY_FULLDETAILS = "insert into campus_staff_tds_computation(TeacherID,pfMonthlyEmplrAmount,pfAmount,esiMonthlyAmount,esiAmount,salaryMonthlyBasic,salaryMonthlyDA,salaryMonthlyHRA,salaryMonthlyTransConveyAllow,salaryMonthlyChildEdu,salaryMonthlySplAllowance,salaryMonthlyArrears,salaryMonthlyPerformIncentive,salaryMonthlyMedicalReimb,salaryMonthlyLeaveEncash,salaryMonthlyFoodCoupon,salaryMonthlyReimbursement,salaryMonthlyInternetExp,salaryMonthlyDriversalary,salaryMonthlyOther,salaryMonthlyTotal,salaryGrossBasic,salaryGrossDA,salaryGrossHRA,salaryGrossTransConveyAllow,salaryGrossChildEdu,salaryGrossSplAllowance,salaryGrossArrears,salaryGrossPerformIncentive,salaryGrossMedicalReimb,salaryGrossLeaveEncash,salaryGrossFoodCoupon,salaryGrossReimbursement,salaryGrossInternetExp,salaryGrossDriverGross,salaryGrossOther,salaryGrossTotal,created_date,created_by,locationId,accyearId) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
	
	public static final String UPDATE_SALARY_FULLDETAILS = "update campus_staff_tds_computation set pfMonthlyEmplrAmount=?,pfAmount=?,esiMonthlyAmount=?,esiAmount=?,salaryMonthlyBasic=?,salaryMonthlyDA=?,salaryMonthlyHRA=?,salaryMonthlyTransConveyAllow=?,salaryMonthlyChildEdu=?,salaryMonthlySplAllowance=?,salaryMonthlyArrears=?,salaryMonthlyPerformIncentive=?,salaryMonthlyMedicalReimb=?,salaryMonthlyLeaveEncash=?,salaryMonthlyFoodCoupon=?,salaryMonthlyReimbursement=?,salaryMonthlyInternetExp=?,salaryMonthlyDriversalary=?,salaryMonthlyOther=?,salaryMonthlyTotal=?,salaryGrossBasic=?,salaryGrossDA=?,salaryGrossHRA=?,salaryGrossTransConveyAllow=?,salaryGrossChildEdu=?,salaryGrossSplAllowance=?,salaryGrossArrears=?,salaryGrossPerformIncentive=?,salaryGrossMedicalReimb=?,salaryGrossLeaveEncash=?,salaryGrossFoodCoupon=?,salaryGrossReimbursement=?,salaryGrossInternetExp=?,salaryGrossDriverGross=?,salaryGrossOther=?,salaryGrossTotal=?,modify_date=?,modify_by=? where TeacherID=?";

	public static final String INSERT_INCOME_SECTION = "insert into campus_staff_income_section(TeacherID,incomeOtherThanSalary,incomeOtherHousingLoanLetout,incomeOtherHousingLoanSelf,incomeOtherTotal,exemptHRA,exemptChildEdu,exemptMedReimb,exemptTransAllowance,exemptLTA,exemptFoodCoupon,exemptTelephoneReimb,exemptCarExpReimb,exemptInternetExp,exemptDriverSal,exemptOtherExp,exemptTotal,section80CEmpPF,section80CTutionFee,section80CFixedDeposit,section80CLIC,section80CMutualFund,section80CNationalSaveCerti,section80CAccruNSC,section80CPublicPF,section80CRepayHousingLoan,section80CULIP,section80CSeniorCitizenSaving,section80CPostSaving,section80COther,section80CTotal,section80DMediClaim1,section80DMediClaim2,section80DMediClaim3,section80DDBMedTreatment1,section80DDBMedTreatment2,section80EEduLoanInterest,section80CCDNPS,section80UDeduction1,section80UDeduction2,section80CCGRajivEquitySaving,section80TTASavingBankInterest,section80DDMedTreatment1,section80DDMedTreatment2,section80D80UTotal,created_date,created_by,locationId,accyearId) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
	
	public static final String UPDATE_INCOME_SECTION = "update campus_staff_income_section set incomeOtherThanSalary=?,incomeOtherHousingLoanLetout=?,incomeOtherHousingLoanSelf=?,incomeOtherTotal=?,exemptHRA=?,exemptChildEdu=?,exemptMedReimb=?,exemptTransAllowance=?,exemptLTA=?,exemptFoodCoupon=?,exemptTelephoneReimb=?,exemptCarExpReimb=?,exemptInternetExp=?,exemptDriverSal=?,exemptOtherExp=?,exemptTotal=?,section80CEmpPF=?,section80CTutionFee=?,section80CFixedDeposit=?,section80CLIC=?,section80CMutualFund=?,section80CNationalSaveCerti=?,section80CAccruNSC=?,section80CPublicPF=?,section80CRepayHousingLoan=?,section80CULIP=?,section80CSeniorCitizenSaving=?,section80CPostSaving=?,section80COther=?,section80CTotal=?,section80DMediClaim1=?,section80DMediClaim2=?,section80DMediClaim3=?,section80DDBMedTreatment1=?,section80DDBMedTreatment2=?,section80EEduLoanInterest=?,section80CCDNPS=?,section80UDeduction1=?,section80UDeduction2=?,section80CCGRajivEquitySaving=?,section80TTASavingBankInterest=?,section80DDMedTreatment1=?,section80DDMedTreatment2=?,section80D80UTotal=?,modify_date=?,modify_by=? where TeacherID=? and locationId=? and accyearId=?";

	public static final String INSERT_HOUSE_RENT = "insert into campus_staff_house_rent(TeacherID,houseRentFromDate,houseRentToDate,houseRentCity,houseRentLandlordName,houseRentAddress,houseRentPANNo,houseRentDeclaredAmount,created_date,created_by,locationId,accyearId) values(?,?,?,?,?,?,?,?,?,?,?,?)";

	public static final String UPDATE_HOUSE_RENT = "update campus_staff_house_rent set houseRentFromDate=?,houseRentToDate=?,houseRentCity=?,houseRentLandlordName=?,houseRentAddress=?,houseRentPANNo=?,houseRentDeclaredAmount=?,modify_date=?,modify_by=? where TeacherID=? and locationId=? and accyearId=?";

	public static final String INSERT_TAX_TDS = "insert into campus_staff_tax_tds_deduction(TeacherID,taxableExemption,taxableAnyOtherIncome,taxworkUnderCapterVIA,taxworkTaxableIncome,taxworkTotalTax,taxworkNetTax,taxworkPerMonth,created_date,created_by,locationId,accyearId) values(?,?,?,?,?,?,?,?,?,?,?,?)";

	public static final String UPDATE_TAX_TDS = "update campus_staff_tax_tds_deduction set taxableExemption=?,taxableAnyOtherIncome=?,taxworkUnderCapterVIA=?,taxworkTaxableIncome=?,taxworkTotalTax=?,taxworkNetTax=?,taxworkPerMonth=?,modify_date=?,modify_by=? where TeacherID=? and locationId=? and accyearId=?";
	
	public static final String UPDATE_TAX_TDS_SALARY = "update campus_staff_salarydetails set TDSTaxbleIncome=?,TDSTaxPayble=?,TDSExemption=?,TDSUnderChapterVIA=?,TDSIncomeFromOther=? where TeacherID=?";
}
