package com.centris.campus.util;

public class StudentAttendanceSqlUtil {
	
	//public static final String GET_ATTENDANCE_LIST = "select distinct s.specilization,s.classsection_id_int,s.classdetail_id_int,ta.AttendenceDate,count(s.student_id_int) as total_streangth,concat(cls.classdetails_name_var,'-',sec.classsection_name_var) classsection,sum(case when ta.attendence='Present' then 1 else 0 end) TotalPresent,sum(case when ta.attendence='Absent' then 1 else 0 end) TotalAbsent,sum(case when ta.attendence='Holiday' then 1 else 0 end) TotalHoliday,sum(case when ta.attendence='Leave' then 1 else 0 end) Totalleave,concat(FirstName,' ',LastName) as teachers,clt.TeacherCode,case when s.specilization = '-' then  '-' else (select Specialization_name from campus_class_specialization  where s.specilization = Specialization_Id and cls.classdetail_id_int = ClassDetails_Id )end Specialization_name from campus_attendence ta,campus_student s,campus_classdetail cls,campus_classsection sec,campus_teachers ct,campus_classteacher clt where ta.AttendenceDate between ? and ? and s.classdetail_id_int=cls.classdetail_id_int and clt.TeacherCode = ct.TeacherID and clt.ClassCode = s.classdetail_id_int and clt.SectionCode = s.classsection_id_int and s.classsection_id_int = sec.classsection_id_int  and s.student_id_int=ta.addmissionno group by ta.AttendenceDate,classsection";
	//public static final String GET_ATTENDANCE_LIST = "select ta.AttendenceDate,csc.specilization,csc.classsection_id_int,csc.classdetail_id_int,count(csc.student_id_int) as total_streangth,concat(cls.classdetails_name_var,'-',sec.classsection_name_var) classsection,sum(case when ta.attendence='Present' then 1 else 0 end) TotalPresent,sum(case when ta.attendence='Absent' then 1 else 0 end) TotalAbsent,sum(case when ta.attendence='Holiday' then 1 else 0 end) TotalHoliday,sum(case when ta.attendence='Leave' then 1 else 0 end) Totalleave,concat(FirstName,' ',LastName) as teachers,clt.TeacherCode,case when csc.specilization = '-' then  '-' else (select spec.Specialization_name from campus_class_specialization spec where csc.specilization = spec.Specialization_Id and cls.classdetail_id_int = spec.ClassDetails_Id )end Specialization_name from campus_attendence ta left join campus_student_classdetails csc on csc.student_id_int=ta.addmissionno left join campus_teachers ct on ct.TeacherID=ta.addmissionno left join campus_classdetail cls on csc.classdetail_id_int=cls.classdetail_id_int left join campus_classsection sec on csc.classsection_id_int = sec.classsection_id_int left join campus_classteacher clt on clt.ClassCode = csc.classdetail_id_int and csc.classsection_id_int=sec.classsection_id_int and clt.TeacherCode = ct.TeacherID where ta.AttendenceDate between ? and ? group by ta.AttendenceDate,classsection";
	//public static final String GET_ATTENDANCE_LIST = "select distinct csc.specilization,csc.classsection_id_int,csc.classdetail_id_int,ta.AttendenceDate,count(s.student_id_int) as total_streangth,concat(cls.classdetails_name_var,'-',sec.classsection_name_var) classsection,sum(case when ta.attendence='Present' then 1 else 0 end) TotalPresent,sum(case when ta.attendence='Absent' then 1 else 0 end) TotalAbsent,sum(case when ta.attendence='Holiday' then 1 else 0 end) TotalHoliday,sum(case when ta.attendence='Leave' then 1 else 0 end) Totalleave,concat(FirstName,' ',LastName) as teachers,clt.TeacherCode,case when csc.specilization = '-' then  '-' else (select Specialization_name from campus_class_specialization  where csc.specilization = Specialization_Id and cls.classdetail_id_int = ClassDetails_Id )end Specialization_name from campus_attendence ta,campus_student s join campus_student_classdetails csc on csc.student_id_int=s.student_id_int,campus_classdetail cls,campus_classsection sec,campus_teachers ct,campus_classteacher clt where ta.AttendenceDate between ? and ? and csc.classdetail_id_int=cls.classdetail_id_int and clt.TeacherCode = ct.TeacherID and clt.ClassCode = csc.classdetail_id_int and clt.SectionCode = csc.classsection_id_int and csc.classsection_id_int = sec.classsection_id_int  and s.student_id_int=ta.addmissionno group by ta.AttendenceDate,classsection";
	//public static final String GET_ATTENDANCE_LIST = "select distinct csc.specilization,csc.classsection_id_int,csc.classdetail_id_int,ta.AttendenceDate,concat(cls.classdetails_name_var,'-',sec.classsection_name_var) classsection,count(s.student_id_int) as total_streangth,sum(case when ta.attendence='Present' then 1 else 0 end) TotalPresent,sum(case when ta.attendence='Absent' then 1 else 0 end) TotalAbsent,sum(case when ta.attendence='Holiday' then 1 else 0 end) TotalHoliday,sum(case when ta.attendence='Leave' then 1 else 0 end) Totalleave,concat(ct.FirstName,' ',ct.LastName) as teachers,clt.TeacherCode,case when csc.specilization = '-' then  '-' else (select Specialization_name from campus_class_specialization  where csc.specilization = Specialization_Id and cls.classdetail_id_int = ClassDetails_Id )end Specialization_name from campus_attendence ta join campus_student s on s.student_id_int=ta.addmissionno left join campus_student_classdetails csc on csc.student_id_int=s.student_id_int left join campus_classdetail cls on csc.classdetail_id_int=cls.classdetail_id_int left join campus_classsection sec on csc.classsection_id_int = sec.classsection_id_int left outer join campus_classteacher clt on clt.ClassCode = csc.classdetail_id_int and clt.SectionCode = csc.classsection_id_int left outer join campus_teachers ct on clt.TeacherCode = ct.TeacherID where ta.AttendenceDate between ? and ? group by ta.AttendenceDate,classsection";
	public static final String GET_ATTENDANCE_LIST = "select ta.locationId,ta.AttendenceDate,csc.specilization,csc.classsection_id_int,csc.classdetail_id_int,count(ta.addmissionno) as total_streangth,concat(cls.classdetails_name_var,'-',sec.classsection_name_var) classsection,sum(case when ta.attendence='Present' then 1 else 0 end) TotalPresent,sum(case when ta.attendence='Absent' then 1 else 0 end) TotalAbsent,sum(case when ta.attendence='Holiday' then 1 else 0 end) TotalHoliday,sum(case when ta.attendence='Leave' then 1 else 0 end) Totalleave,concat(ct.FirstName,' ',ct.LastName) as teachers,clt.TeacherCode,case when csc.specilization = '-' then  '-' else (select Specialization_name from campus_class_specialization  where csc.specilization = Specialization_Id and cls.classdetail_id_int = ClassDetails_Id )end Specialization_name from campus_attendence ta join campus_classteacher clt on clt.TeacherCode=ta.teacherId and ta.locationId=clt.locationId join campus_student_classdetails csc on clt.ClassCode = csc.classdetail_id_int and clt.SectionCode = csc.classsection_id_int and csc.student_id_int=ta.addmissionno and csc.locationId=clt.locationId join campus_classdetail cls on clt.ClassCode = cls.classdetail_id_int and clt.locationId=cls.locationId join campus_classsection sec on clt.SectionCode = sec.classsection_id_int and clt.locationId=sec.locationId join campus_teachers ct on clt.TeacherCode = ct.TeacherID where ta.AttendenceDate between ? and ? group by ta.AttendenceDate,classsection";

	//public static final String GET_STUDENT_ATTENDANCE_LIST = "select s.student_id_int,s.student_admissionno_var,concat(s.student_fname_var,' ',s.student_lname_var) studentname,cd.classdetails_name_var,se.classsection_name_var,case when a.attendence is null then 'Present' else a.attendence end status,case when period1 is null then 'Present' else period1 end period1Status,case when period2 is null then 'Present' else period2 end period2Status,case when period3 is null then 'Present' else period3 end period3Status,case when period4 is null then 'Present' else period4 end period4Status,case when period5 is null then 'Present' else period5 end period5Status,case when period6 is null then 'Present' else period6 end period6Status,case when period7 is null then 'Present' else period7 end period7Status,case when period8 is null then 'Present' else period8 end period8Status,case when period9 is null then 'Present' else period9 end period9Status from  campus_student s left outer join campus_attendence a on a.addmissionno=s.student_id_int and a.attendencedate=?,campus_classdetail cd,campus_classsection se  where s.classdetail_id_int=cd.classdetail_id_int and s.classsection_id_int=se.classsection_id_int and s.classdetail_id_int like ? and s.classsection_id_int like ? order by length(s.student_admissionno_var),s.student_admissionno_var";
	//public static final String GET_STUDENT_ATTENDANCE_LIST ="select distinct s.student_id_int,s.student_admissionno_var,concat(s.student_fname_var,' ',s.student_lname_var) studentname,cd.classdetails_name_var,se.classsection_name_var,case when a.attendence is null then 'Present' else a.attendence end status,case when period1 is null then 'Present' else period1 end period1Status,case when period2 is null then 'Present' else period2 end period2Status,case when period3 is null then 'Present' else period3 end period3Status,case when period4 is null then 'Present' else period4 end period4Status,case when period5 is null then 'Present' else period5 end period5Status,case when period6 is null then 'Present' else period6 end period6Status,case when period7 is null then 'Present' else period7 end period7Status,case when period8 is null then 'Present' else period8 end period8Status,case when period9 is null then 'Present' else period9 end period9Status from  campus_student s left outer join campus_attendence a on a.addmissionno=s.student_id_int and a.attendencedate=? left join campus_student_classdetails csc on csc.student_id_int=s.student_id_int,campus_classdetail cd,campus_classsection se  where csc.classdetail_id_int=cd.classdetail_id_int and csc.classsection_id_int=se.classsection_id_int and csc.classdetail_id_int like ? and csc.classsection_id_int like ? order by length(s.student_admissionno_var),s.student_admissionno_var";
	
	
	public static final String GET_STUDENT_ATTENDANCE_LIST ="select distinct s.student_id_int,s.student_admissionno_var,concat(s.student_fname_var,' ',s.student_lname_var) studentname,cd.classdetails_name_var,se.classsection_name_var,a.locationId,case when a.attendence is null then 'Present' else a.attendence end status,case when period1 is null then 'Present' else period1 end period1Status,case when period2 is null then 'Present' else period2 end period2Status,case when period3 is null then 'Present' else period3 end period3Status,case when period4 is null then 'Present' else period4 end period4Status,case when period5 is null then 'Present' else period5 end period5Status,case when period6 is null then 'Present' else period6 end period6Status,case when period7 is null then 'Present' else period7 end period7Status,case when period8 is null then 'Present' else period8 end period8Status,case when period9 is null then 'Present' else period9 end period9Status from campus_student s left join campus_student_classdetails csc on csc.student_id_int=s.student_id_int left outer join campus_attendence a on a.addmissionno=s.student_id_int and a.attendencedate=?,campus_classdetail cd,campus_classsection se where csc.classdetail_id_int=cd.classdetail_id_int and csc.classsection_id_int=se.classsection_id_int and csc.classdetail_id_int like ? and csc.classsection_id_int like ? and specilization like '-' order by studentname,length(s.student_admissionno_var),s.student_admissionno_var";
	
	//public static final String GET_SPEC_STUDENT_ATTENDANCE_LIST = "select s.student_id_int,s.student_admissionno_var,concat(s.student_fname_var,' ',s.student_lname_var) studentname,cd.classdetails_name_var,se.classsection_name_var,case when a.attendence is null then 'Present' else a.attendence end status,case when period1 is null then 'Present' else period1 end period1Status,case when period2 is null then 'Present' else period2 end period2Status,case when period3 is null then 'Present' else period3 end period3Status,case when period4 is null then 'Present' else period4 end period4Status,case when period5 is null then 'Present' else period5 end period5Status,case when period6 is null then 'Present' else period6 end period6Status,case when period7 is null then 'Present' else period7 end period7Status,case when period8 is null then 'Present' else period8 end period8Status,case when period9 is null then 'Present' else period9 end period9Status from  campus_student s left outer join campus_attendence a on a.addmissionno=s.student_id_int and a.attendencedate=?,campus_classdetail cd,campus_classsection se  where s.classdetail_id_int=cd.classdetail_id_int and s.classsection_id_int=se.classsection_id_int and s.classdetail_id_int like ? and s.classsection_id_int like ? and specilization like ? order by length(s.student_admissionno_var),s.student_admissionno_var";
	public static final String GET_SPEC_STUDENT_ATTENDANCE_LIST = "select distinct s.student_id_int,s.student_admissionno_var,concat(s.student_fname_var,' ',s.student_lname_var) studentname,cd.classdetails_name_var,se.classsection_name_var,a.locationId,case when a.attendence is null then 'Present' else a.attendence end status,case when period1 is null then 'Present' else period1 end period1Status,case when period2 is null then 'Present' else period2 end period2Status,case when period3 is null then 'Present' else period3 end period3Status,case when period4 is null then 'Present' else period4 end period4Status,case when period5 is null then 'Present' else period5 end period5Status,case when period6 is null then 'Present' else period6 end period6Status,case when period7 is null then 'Present' else period7 end period7Status,case when period8 is null then 'Present' else period8 end period8Status,case when period9 is null then 'Present' else period9 end period9Status from campus_student s left join campus_student_classdetails csc on csc.student_id_int=s.student_id_int left outer join campus_attendence a on a.addmissionno=s.student_id_int and a.attendencedate=?,campus_classdetail cd,campus_classsection se where csc.classdetail_id_int=cd.classdetail_id_int and csc.classsection_id_int=se.classsection_id_int and csc.classdetail_id_int like ? and csc.classsection_id_int like ? and specilization like ? order by studentname,length(s.student_admissionno_var),s.student_admissionno_var";
	
	public static final String GET_ATTENDANCE_COUNT = "select count(*) from campus_attendence where addmissionno=? and AttendenceDate=?";
	
	public static final String UPDATE_ATTENDANCE = "update campus_attendence set attendence=?,updatedBy=?,updateDate=?,period1=?,period2=?,period3=?,period4=?,period5=?,period6=?,period7=?,period8=?,period9=? where  addmissionno=? and attendencedate=?";
	
	public static final String INSERT_ATTENDANCE ="insert into campus_attendence(addmissionno,attendencedate,attendence,createdBy,CreateDate,period1,period2,period3,period4,period5,period6,period7,period8,period9,teacherId,locationId) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

	public static final String GET_STU_PERIOD_ATT ="select * from campus_student_period_attendance where AttendanceDate=? and StudentId=?";

	public static final String UPDATE_STU_PERIOD_ATT = "update campus_student_period_attendance set  Period1=?,Period2=?,Period3=?,Period4=?,Period5=?,Period6=?,Period7=?,Period8=?,UpdatedBy=?,UpdateDate=? where AttendanceDate=? and StudentId=?";
	
	public static final String INSERT_STU_PERIOD_ATT = "insert into campus_student_period_attendance(AttendanceDate,StudentId,Period1,Period2,Period3,Period4,Period5,Period6,Period7,Period8,CreatedBy,CreateDate) values(?,?,?,?,?,?,?,?,?,?,?,?)";
	
	public static final String CHECK_STU_PERIOD_ATT = "select count(*) from campus_student_period_attendance where AttendanceDate=? and StudentId=?";

	public static final String GET_TEACHERBY_CLASS = "select concat(FirstName,' ',LastName) as teacher,TeacherID from campus_teachers,campus_classteacher where TeacherCode = TeacherID and ClassCode = ? and SectionCode = ?";

	public static final String GET_SEARCH_ATTENDANCE_LIST = "select ta.AttendenceDate,csc.specilization,csc.classsection_id_int,csc.classdetail_id_int,count(ta.addmissionno) as total_streangth,concat(cls.classdetails_name_var,'-',sec.classsection_name_var) classsection,sum(case when ta.attendence='Present' then 1 else 0 end) TotalPresent,sum(case when ta.attendence='Absent' then 1 else 0 end) TotalAbsent,sum(case when ta.attendence='Holiday' then 1 else 0 end) TotalHoliday,sum(case when ta.attendence='Leave' then 1 else 0 end) Totalleave,concat(ct.FirstName,' ',ct.LastName) as teachers,clt.TeacherCode,case when csc.specilization = '-' then  '-' else (select Specialization_name from campus_class_specialization  where csc.specilization = Specialization_Id and cls.classdetail_id_int = ClassDetails_Id )end Specialization_name from campus_attendence ta join campus_classteacher clt on clt.TeacherCode=ta.teacherId and ta.locationId=clt.locationId join campus_student_classdetails csc on clt.ClassCode = csc.classdetail_id_int and clt.SectionCode = csc.classsection_id_int and csc.student_id_int=ta.addmissionno and csc.locationId=clt.locationId join campus_classdetail cls on clt.ClassCode = cls.classdetail_id_int and clt.locationId=cls.locationId join campus_classsection sec on clt.SectionCode = sec.classsection_id_int and clt.locationId=sec.locationId join campus_teachers ct on clt.TeacherCode = ct.TeacherID where ta.locationId like ? and ta.AttendenceDate>=? and ta.AttendenceDate<=? group by ta.AttendenceDate,classsection";
	
	public static final String GET_CLASS_ATTENDANCE_LIST = "select ta.AttendenceDate,csc.specilization,csc.classsection_id_int,csc.classdetail_id_int,count(ta.addmissionno) as total_streangth,concat(cls.classdetails_name_var,'-',sec.classsection_name_var) classsection,sum(case when ta.attendence='Present' then 1 else 0 end) TotalPresent,sum(case when ta.attendence='Absent' then 1 else 0 end) TotalAbsent,sum(case when ta.attendence='Holiday' then 1 else 0 end) TotalHoliday,sum(case when ta.attendence='Leave' then 1 else 0 end) Totalleave,concat(ct.FirstName,' ',ct.LastName) as teachers,clt.TeacherCode,case when csc.specilization = '-' then  '-' else (select Specialization_name from campus_class_specialization  where csc.specilization = Specialization_Id and cls.classdetail_id_int = ClassDetails_Id )end Specialization_name from campus_attendence ta join campus_classteacher clt on clt.TeacherCode=ta.teacherId and ta.locationId=clt.locationId join campus_student_classdetails csc on clt.ClassCode = csc.classdetail_id_int and clt.SectionCode = csc.classsection_id_int and csc.student_id_int=ta.addmissionno and csc.locationId=clt.locationId join campus_classdetail cls on clt.ClassCode = cls.classdetail_id_int and clt.locationId=cls.locationId join campus_classsection sec on clt.SectionCode = sec.classsection_id_int and clt.locationId=sec.locationId join campus_teachers ct on clt.TeacherCode = ct.TeacherID where ta.locationId like ? and clt.ClassCode like ? group by ta.AttendenceDate,classsection";
	
	public static final String GET_CLASS_SECTION_ATTENDANCE_LIST = "select ta.AttendenceDate,csc.specilization,csc.classsection_id_int,csc.classdetail_id_int,count(ta.addmissionno) as total_streangth,concat(cls.classdetails_name_var,'-',sec.classsection_name_var) classsection,sum(case when ta.attendence='Present' then 1 else 0 end) TotalPresent,sum(case when ta.attendence='Absent' then 1 else 0 end) TotalAbsent,sum(case when ta.attendence='Holiday' then 1 else 0 end) TotalHoliday,sum(case when ta.attendence='Leave' then 1 else 0 end) Totalleave,concat(ct.FirstName,' ',ct.LastName) as teachers,clt.TeacherCode,case when csc.specilization = '-' then  '-' else (select Specialization_name from campus_class_specialization  where csc.specilization = Specialization_Id and cls.classdetail_id_int = ClassDetails_Id )end Specialization_name from campus_attendence ta join campus_classteacher clt on clt.TeacherCode=ta.teacherId and ta.locationId=clt.locationId join campus_student_classdetails csc on clt.ClassCode = csc.classdetail_id_int and clt.SectionCode = csc.classsection_id_int and csc.student_id_int=ta.addmissionno and csc.locationId=clt.locationId join campus_classdetail cls on clt.ClassCode = cls.classdetail_id_int and clt.locationId=cls.locationId join campus_classsection sec on clt.SectionCode = sec.classsection_id_int and clt.locationId=sec.locationId join campus_teachers ct on clt.TeacherCode = ct.TeacherID where ta.locationId like ? and clt.ClassCode like ? and clt.SectionCode like ? group by ta.AttendenceDate,classsection";
	
	public static final String GET_TEACHER_LIST = "select TeacherID,concat(FirstName,' ',LastName) as teachername from campus_teachers where Loc_ID like ? order by teachername";

	public static final String GET_ATTENDANCE_LIST_BY_TEACHER = "select ta.AttendenceDate,csc.specilization,csc.classsection_id_int,csc.classdetail_id_int,count(ta.addmissionno) as total_streangth,concat(cls.classdetails_name_var,'-',sec.classsection_name_var) classsection,sum(case when ta.attendence='Present' then 1 else 0 end) TotalPresent,sum(case when ta.attendence='Absent' then 1 else 0 end) TotalAbsent,sum(case when ta.attendence='Holiday' then 1 else 0 end) TotalHoliday,sum(case when ta.attendence='Leave' then 1 else 0 end) Totalleave,concat(ct.FirstName,' ',ct.LastName) as teachers,clt.TeacherCode,case when csc.specilization = '-' then  '-' else (select Specialization_name from campus_class_specialization  where csc.specilization = Specialization_Id and cls.classdetail_id_int = ClassDetails_Id )end Specialization_name from campus_attendence ta join campus_classteacher clt on clt.TeacherCode=ta.teacherId and ta.locationId=clt.locationId join campus_student_classdetails csc on clt.ClassCode = csc.classdetail_id_int and clt.SectionCode = csc.classsection_id_int and csc.student_id_int=ta.addmissionno and csc.locationId=clt.locationId join campus_classdetail cls on clt.ClassCode = cls.classdetail_id_int and clt.locationId=cls.locationId join campus_classsection sec on clt.SectionCode = sec.classsection_id_int and clt.locationId=sec.locationId join campus_teachers ct on clt.TeacherCode = ct.TeacherID where ta.locationId like ? and clt.ClassCode like ? and clt.SectionCode like ? and clt.TeacherCode like ? group by ta.AttendenceDate,classsection";

	public static final String GET_ACADAMICYEAR_DATE = "select startDate,endDate from campus_acadamicyear where acadamic_id=?";
	
	public static final String GET_ATTENDANCE_LIST_BY_DATE = "select ta.AttendenceDate,csc.specilization,csc.classsection_id_int,csc.classdetail_id_int,count(ta.addmissionno) as total_streangth,concat(cls.classdetails_name_var,'-',sec.classsection_name_var) classsection,sum(case when ta.attendence='Present' then 1 else 0 end) TotalPresent,sum(case when ta.attendence='Absent' then 1 else 0 end) TotalAbsent,sum(case when ta.attendence='Holiday' then 1 else 0 end) TotalHoliday,sum(case when ta.attendence='Leave' then 1 else 0 end) Totalleave,concat(ct.FirstName,' ',ct.LastName) as teachers,clt.TeacherCode,case when csc.specilization = '-' then  '-' else (select Specialization_name from campus_class_specialization  where csc.specilization = Specialization_Id and cls.classdetail_id_int = ClassDetails_Id )end Specialization_name from campus_attendence ta join campus_classteacher clt on clt.TeacherCode=ta.teacherId and ta.locationId=clt.locationId join campus_student_classdetails csc on clt.ClassCode = csc.classdetail_id_int and clt.SectionCode = csc.classsection_id_int and csc.student_id_int=ta.addmissionno and csc.locationId=clt.locationId join campus_classdetail cls on clt.ClassCode = cls.classdetail_id_int and clt.locationId=cls.locationId join campus_classsection sec on clt.SectionCode = sec.classsection_id_int and clt.locationId=sec.locationId join campus_teachers ct on clt.TeacherCode = ct.TeacherID where ta.AttendenceDate between ? and ? group by ta.AttendenceDate,classsection";
}


