package com.centris.campus.util;

public class StudentEnquirySqlUtil {
	public static final String GET_INACTIVE_ENQUIRY_DETAILS = "select case when enq.lname is null then enq.fname else concat(enq.fname,' ',enq.lname)end StudentName,enq.enquiry_id,enq.age,cd.classdetails_name_var ClassName,enq.contact_name,enq.contact_mobileno,isJoined,enq.interaction_Status,enq.registration_Status,enq.address from campus_student_enquiry enq join campus_classdetail cd on enq.classdetail_id = cd.classdetail_id_int join campus_acadamicyear acc on enq.acadamicyear_id=acc.acadamic_id order by enq.create_user asc";
	public static final String GET_SELECTED_ENQUIRY_DETAILS = "select enq.enquiry_id,enq.application_no,enq.fname,enq.lname,enq.acadamicyear_id,enq.dob,enq.gender,enq.age,enq.expec_doj,enq.religion,enq.physically_challenged,enq.contact_type,enq.contact_name,enq.contact_mobileno,enq.contact_mailid,enq.address,enq.classdetail_id,enq.enquiredby,enq.interaction_Status,enq.registration_Status,enq.interaction_date,enq.registration_date,enq.isJoined from campus_student_enquiry enq where enq.isJoined='N'and enq.enquiry_id=?";
	public static final String UPDATE_ENQUIRY_DETAILS = "update campus_student_enquiry set isJoined=?,studentId=?,modified_user=?,modified_date=? where enquiry_id=?";
	public static final String RE_ADMISSION_STUDENT_SEARCH = "select student_fname_var,student_id_int from campus_student where fms_acadamicyear_id_int =? and classdetail_id_int like ? and classsection_id_int like ? and student_fname_var like ?";
	public static final String RE_ADMISSION_STUDENT_DETAIL_BY_SEARCH_TERM = "select st.isRTE,st.isConcession,st.student_fname_var,st.student_lname_var,st.student_id_int,st.student_rollno,st.student_admissionno_var,student_application_no,isTransport,isHostel,st.fms_classstream_id_int,st.fms_acadamicyear_id_int,st.classdetail_id_int,st.classsection_id_int,st.student_regno_var,st.student_dob_var,st.student_gender_var,st.student_bloodgroup_var,st.student_age_int,st.student_imgurl_var,st.student_doj_var,st.student_religion_var,st.student_nationality_var,st.student_scholorship_var,st.student_promotionstatus,st.student_physicallychallenged,st.student_identificationmarks_var,st.student_grade,st.student_fathername_var,st.student_mothername_var,st.student_gaurdianname_var,st.student_fatherqualification_var,st.student_fathermobileno_var,st.student_mothermobileno_var,st.student_motherqualification_var,st.student_street1,st.student_street2,st.student_location,st.student_towncity,st.student_zippostcode,st.student_state,st.student_country,st.student_siblingname_var,st.student_siblingclass_var,st.student_status_var,st.student_prehistory_var,st.student_remarks_var,st.student_quota,st.student_father_mailid,st.student_mother_mailid,st.student_gardian_mailid,st.student_gardian_mobileno,st.student_caste,par.ParentID,cpr.relationship from campus_student st join campus_classstream strm on strm.classstream_id_int=st.fms_classstream_id_int join campus_classdetail cd on cd.classdetail_id_int=st.classdetail_id_int join campus_classsection sec on sec.classsection_id_int=st.classsection_id_int join campus_acadamicyear acc on acc.acadamicyear_id_int=st.fms_acadamicyear_id_int join campus_quota qt on qt.Quota_Code=st.student_quota join campus_parentchildrelation cpr on cpr.stu_addmissionNo=st.student_admissionno_var join campus_parents par on cpr.parentid=par.ParentID where  st.student_id_int=?";
	public static final String INSERTING_ENQUIRY_VALUES = "insert into campus_student_enquiry(enquiry_id, application_no,acadamicyear_id, classdetail_id, fname,lname,dob, gender, age, expec_doj, religion, physically_challenged, contact_type, contact_name, contact_mobileno,contact_mailid,enquiredby,address,create_user,create_date,interaction_Status,interaction_date,registration_Status,registration_date) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,now(),?,?,?,?)";
	public static final String DUBNLICATE_CHECKING = "select count(*) from campus_student_enquiry where fname = ? and dob = ? and gender = ? and physically_challenged = ? and classstream_id = ?  and classdetail_id= ?  and acadamicyear_id = ? and contact_type = ? and contact_name = ? and contact_mobileno = ?";
	public static final String VALIDATION_MOBILE_NO = "select count(*) from campus_student_enquiry where contact_mobileno = ?";
	public static final String GET_ENQUIRY_DETAILS_BYSEARCH = "select case when enq.lname is null then enq.fname else concat(enq.fname,' ',enq.lname)end StudentName,cd.classdetails_name_var ClassName ,enq.enquiry_id,enq.classstream_id,enq.acadamicyear_id,enq.classdetail_id,enq.fname,enq.lname,enq.dob,enq.gender,enq.age,enq.expec_doj,enq.religion,enq.physically_challenged,enq.contact_type,enq.contact_name,enq.contact_mobileno,enq.contact_mailid,enq.street1,enq.street2,enq.location,enq.towncity,enq.zippostcode,enq.state,enq.country,isJoined,enq.studentId,enq.interaction_Status,enq.registration_Status,enq.enquiredby from campus_student_enquiry enq  join campus_classstream cls on cls.classstream_id_int=enq.classstream_id  join campus_classdetail cd on cd.classdetail_id_int=enq.classdetail_id  join campus_acadamicyear acc on acc.acadamicyear_id_int=enq.acadamicyear_id where enq.create_date like ? and concat(enq.fname,'',enq.lname) like ? and enq.interaction_Status like ? and enq.registration_Status like ? order by enq.create_user asc";
	public static final String ALL_TEACHER_DETAILS = "select concat(t.FirstName,'',t.LastName) as teacherName,t.Qualification,d.designationName,t.MobileNo,t.TeacherID,t.email from campus_teachers t,campus_designation d where t.designation=d.DesignationCode and t.tstatus='active' ";
	public static final String TEACHER_DETAILS_BY_SEARCHTERM = "select case when t.LastName is null then t.FirstName else concat(t.FirstName,'',t.LastName) end teacherName,t.Qualification, des.designationName designation,t.MobileNo,t.TeacherID,t.email from campus_teachers t join campus_designation des on des.DesignationCode=t.designation where t.Qualification like ? or t.designation like ? or t.MobileNo like ? or t.email like ?  or concat(t.FirstName,'',t.LastName) like ? or concat(t.FirstName,' ',t.LastName) like ? and t.tstatus='active'";
	public static final String TEACHER_DETAILS_BY_ID = "select te.FirstName,te.image,te.Qualification,te.designation,te.MobileNo,te.TeacherID,te.email,te.DateOfBirth,te.DateOfJoining,te.Type,te.Address,su.subjectName,des.designationName,dept.DEPT_NAME from campus_teachers te left outer join campus_subject su on su.subjectID=te.Subject_specialization1,campus_designation des,campus_department dept where te.TeacherID =? and te.designation=des.DesignationCode and te.department=dept.DEPT_ID";
	public static final String UPDATE_ENQUIRY_STUDENT_DETAILS = "update campus_student_enquiry set acadamicyear_id = ?,classdetail_id = ?,fname = ?, lname = ?,dob = ?,gender = ?, age = ?, expec_doj = ?, religion = ?, physically_challenged = ?, contact_type= ?, contact_name= ?, contact_mobileno= ?, contact_mailid= ?, modified_user= ?, modified_date= now(),interaction_Status= ?, registration_Status= ?, application_no = ?, interaction_date= ?, registration_date= ?,address=?  where enquiry_id = ?";

	public static final String VALIDATION_APPLICATION_NO = "select count(*) from campus_student_enquiry where application_no = ?";

	public static final String CHECK_APPLICATION_NUMBER = "select count(*) from campus_student where (student_application_no<> '' and student_application_no=?)";
	public static final String CHECKING_STUDENT_VALIDATION = "select count(*) from campus_student_enquiry where fname = ? and dob = ? and gender = ? and physically_challenged = ? and classdetail_id= ?  and acadamicyear_id = ? and contact_type = ? and contact_name = ? and contact_mobileno = ? and application_no=? and enquiry_id != ?";
	public static final String VALIDATION_PHONE_NO = "select count(*) from campus_student_enquiry where contact_mobileno = ? and enquiry_id != ?";
	public static final String DELETE_STUDENT_ENQUIRY = "delete from campus_student_enquiry where enquiry_id = ?";

	public static final String GET_INACTIVE_ENQUIRY_DETAILS_SEARCH = "select case when enq.lname is null then enq.fname else concat(enq.fname,' ',enq.lname)end StudentName,enq.enquiry_id,enq.age,cd.classdetails_name_var ClassName,enq.contact_name,enq.contact_mobileno,isJoined,enq.interaction_Status,enq.registration_Status,enq.address from campus_student_enquiry enq join campus_classdetail cd on enq.classdetail_id = cd.classdetail_id_int join campus_acadamicyear acc on enq.acadamicyear_id=acc.acadamic_id where enq.fname like ? or enq.lname like ?  order by enq.create_user asc ";
}
