package com.centris.campus.util;

public class StudentCertificatesSqlConstants {

	public static final String GET_STUDENTS_CERTIFICATE ="select distinct st.student_id_int,cstd.fms_acadamicyear_id_int,cstd.locationId,cstd.classdetail_id_int,cstd.classsection_id_int,cstd.student_rollno,st.student_admissionno_var,case when st.student_lname_var is null then st.student_fname_var else concat(st.student_fname_var,' ',st.student_lname_var)end studentName,cls.classdetails_name_var,sec.classsection_name_var from campus_student st join campus_student_classdetails cstd on st.student_id_int=cstd.student_id_int join campus_classdetail cls on cls.classdetail_id_int=cstd.classdetail_id_int join campus_classsection sec on sec.classsection_id_int=cstd.classsection_id_int join campus_acadamicyear acc on acc.acadamic_id=cstd.fms_acadamicyear_id_int where cstd.locationId like ? and cstd.fms_acadamicyear_id_int like ? order by length(cstd.classdetail_id_int),cstd.classdetail_id_int,classsection_name_var,studentName" ;
	public static final String GET_STUDENTS_DETAILS = "select  csc.classdetail_id_int,csc.locationId,csc.classsection_id_int,csc.fms_acadamicyear_id_int,par.address,st.student_gender_var,csc.student_imgurl_var,st.student_dob_var,classdetails_name_var,classsection_name_var,concat(st.student_fname_var,' ',st.student_lname_var) as studentName,acc.acadamic_year,loc.Location_Name,st.student_admissionno_var,par.FatherName,par.student_mothername_var from campus_student st join campus_parentchildrelation pa on st.student_id_int= pa.stu_addmissionNo join campus_parents par on pa.parentid = par.ParentID join campus_student_classdetails csc  on csc.student_id_int = st.student_id_int join campus_classdetail cd on cd.classdetail_id_int = csc.classdetail_id_int join campus_classsection sc on sc.classsection_id_int = csc.classsection_id_int join campus_acadamicyear acc on acc.acadamic_id = csc.fms_acadamicyear_id_int join campus_location loc on loc.Location_Id = csc.locationId where sc.locationId = csc.locationId and cd.locationId = csc.locationId and  st.student_id_int = ? and csc.fms_acadamicyear_id_int = ? and csc.locationId like ? ";
	public static final String ADD_AGE_CERTIFICATE = "insert into campus_student_age_certificate(AgeCertificate_id,Accyear_id,loc_id,stuId,classId,sectionId,purpose,otherInfo,studentStatus) values(?,?,?,?,?,?,?,?,?)";
	public static final String ADD_BONAFIED_CERTIFICATE = "insert into campus_student_bonafied_certificate (bonafiedcertiid,stuid,classid,sectionid,accyearid,locid,purpose,otherinfo,studentstatus) values(?,?,?,?,?,?,?,?,?)";
	public static final String ADD_CONDUCTED_CERTIFICATE = "insert into campus_student_conduct_certificate(conductedcetificate_id,accyear_id,loc_id,stu_id,class_id,section_id,purpose,otherinfo,conductno,conduct,studentstatus)values(?,?,?,?,?,?,?,?,?,?,?)";
	public static final String ADD_COURSE_CONDUCTED_CERTIFICATE = "insert into campus_student_course_conduct_cetificate(course_conduct_certifi_id,accyear_id,loc_id,stu_id,class_id,section_id,purpose,otherinfo,conductno,conduct,studentstatus)values(?,?,?,?,?,?,?,?,?,?,?)";
	public static final String ADD_STUDENT_VISA_CERTIFICATE = "insert into campus_student_visa_certificate(studentvisa_id,accyear_id,loc_id,stu_id,class_id,section_id,purpose,passportNo,studentstatus)values(?,?,?,?,?,?,?,?,?)";
	public static final String GET_DISPLAY_STUDENTS_CERTIFICATE = "select  acc.acadamic_year,cs.classsection_name_var,cd.classdetails_name_var,loc.Location_Name,par.address,st.student_gender_var,sac.purpose,sac.otherInfo,sac.studentStatus,st.student_imgurl_var,st.student_dob_var,concat(st.student_fname_var,' ',st.student_lname_var) as studentName,st.student_admissionno_var,par.FatherName,par.student_mothername_var from  campus_student st join campus_parentchildrelation pa on st.student_id_int= pa.stu_addmissionNo join campus_parents par on pa.parentid = par.ParentID join campus_student_age_certificate sac on sac.stuId = st.student_id_int join campus_acadamicyear acc on acc.acadamic_id = sac.Accyear_id join campus_classdetail cd on cd.classdetail_id_int = sac.classId join campus_classsection cs on cs.classsection_id_int = sac.sectionId join campus_location loc on loc.Location_Id = sac.loc_id where cd.locationId = sac.loc_id and cs.locationId = sac.loc_id and st.student_id_int = ? and sac.AgeCertificate_id = ?";
	public static final String GET_DISPLAY_BONAFIED_CERTIFICATE = "select  acc.acadamic_year,cs.classsection_name_var,cd.classdetails_name_var,loc.Location_Name,par.address,st.student_gender_var,sbc.purpose,sbc.otherinfo,sbc.studentstatus,st.student_imgurl_var,st.student_dob_var,concat(st.student_fname_var,' ',st.student_lname_var) as studentName,st.student_admissionno_var,par.FatherName,par.student_mothername_var from  campus_student st join campus_parentchildrelation pa on st.student_id_int= pa.stu_addmissionNo join campus_parents par on pa.parentid = par.ParentID join campus_student_bonafied_certificate sbc on sbc.stuid = st.student_id_int join campus_acadamicyear acc on acc.acadamic_id = sbc.accyearid join campus_classdetail cd on cd.classdetail_id_int = sbc.classid join campus_classsection cs on cs.classsection_id_int = sbc.sectionid join campus_location loc on loc.Location_Id = sbc.locid where cd.locationId = sbc.locid and cs.locationId = sbc.locid and st.student_id_int = ? and sbc.bonafiedcertiid = ?";
	public static final String GET_DISPLAY_CONDUCT_CERTIFICATE = "select  acc.acadamic_year,cs.classsection_name_var,cd.classdetails_name_var,loc.Location_Name,par.address,st.student_gender_var,sbc.purpose,sbc.otherinfo,sbc.conductno,sbc.conduct,sbc.studentstatus,st.student_imgurl_var,st.student_dob_var,concat(st.student_fname_var,' ',st.student_lname_var) as studentName,st.student_admissionno_var,par.FatherName,par.student_mothername_var from  campus_student st join campus_parentchildrelation pa on st.student_id_int= pa.stu_addmissionNo join campus_parents par on pa.parentid = par.ParentID join campus_student_conduct_certificate sbc on sbc.stu_id = st.student_id_int join campus_acadamicyear acc on acc.acadamic_id = sbc.accyear_id join campus_classdetail cd on cd.classdetail_id_int = sbc.class_id join campus_classsection cs on cs.classsection_id_int = sbc.section_id join campus_location loc on loc.Location_Id = sbc.loc_id where cd.locationId = sbc.loc_id and cs.locationId = sbc.loc_id and st.student_id_int = ? and sbc.conductedcetificate_id = ?";
	public static final String GET_DISPLAY_COURSECONDUCT_CERTIFICATE = "select  acc.acadamic_year,cs.classsection_name_var,cd.classdetails_name_var,loc.Location_Name,par.address,st.student_gender_var,sbc.purpose,sbc.otherinfo,sbc.conductno,sbc.conduct,sbc.studentstatus,st.student_imgurl_var,st.student_dob_var,concat(st.student_fname_var,' ',st.student_lname_var) as studentName,st.student_admissionno_var,par.FatherName,par.student_mothername_var from  campus_student st join campus_parentchildrelation pa on st.student_id_int= pa.stu_addmissionNo join campus_parents par on pa.parentid = par.ParentID join campus_student_course_conduct_cetificate sbc on sbc.stu_id = st.student_id_int join campus_acadamicyear acc on acc.acadamic_id = sbc.accyear_id join campus_classdetail cd on cd.classdetail_id_int = sbc.class_id join campus_classsection cs on cs.classsection_id_int = sbc.section_id join campus_location loc on loc.Location_Id = sbc.loc_id where cd.locationId = sbc.loc_id and cs.locationId = sbc.loc_id and st.student_id_int = ? and sbc.course_conduct_certifi_id = ?";
	public static final String GET_DISPLAY_STUDENTVISA_CERTIFICATE = "select  acc.acadamic_year,cs.classsection_name_var,cd.classdetails_name_var,loc.Location_Name,par.address,st.student_gender_var,sbc.purpose,sbc.passportNo,sbc.studentstatus,st.student_imgurl_var,st.student_dob_var,concat(st.student_fname_var,' ',st.student_lname_var) as studentName,st.student_admissionno_var,par.FatherName,par.student_mothername_var from  campus_student st join campus_parentchildrelation pa on st.student_id_int= pa.stu_addmissionNo join campus_parents par on pa.parentid = par.ParentID join campus_student_visa_certificate sbc on sbc.stu_id = st.student_id_int join campus_acadamicyear acc on acc.acadamic_id = sbc.accyear_id join campus_classdetail cd on cd.classdetail_id_int = sbc.class_id join campus_classsection cs on cs.classsection_id_int = sbc.section_id join campus_location loc on loc.Location_Id = sbc.loc_id where cd.locationId = sbc.loc_id and cs.locationId = sbc.loc_id and st.student_id_int = ? and sbc.studentvisa_id = ?";
	
}
