package com.centris.campus.admin;
// Generated Aug 28, 2013 11:05:25 PM by Hibernate Tools 3.2.1.GA


import java.sql.Date;
import java.sql.Timestamp;

/**
 * LstmsParents generated by hbm2java
 */
public class LstmsParents  implements java.io.Serializable {


     private String parentId;
     private String firstName;
     private String lastName;
     private String qualification;
     private String address;
     private String mobileno;
     private String userName;
     private String gender;
     private String email;
     private Timestamp createdate;
     private String modifiedby;
     private String validatedby;
     private Date lasttimevisit;
     private String pstatus;
     private String password;

    public LstmsParents() {
    }

	
    public LstmsParents(String parentId, String address, String userName, String gender, Timestamp createdate, Date lasttimevisit) {
        this.parentId = parentId;
        this.address = address;
        this.userName = userName;
        this.gender = gender;
        this.createdate = createdate;
        this.lasttimevisit = lasttimevisit;
    }
    public LstmsParents(String parentId, String firstName, String lastName, String qualification, String address, String mobileno, String userName, String gender, String email, Timestamp createdate, String modifiedby, String validatedby, Date lasttimevisit, String pstatus, String password) {
       this.parentId = parentId;
       this.firstName = firstName;
       this.lastName = lastName;
       this.qualification = qualification;
       this.address = address;
       this.mobileno = mobileno;
       this.userName = userName;
       this.gender = gender;
       this.email = email;
       this.createdate = createdate;
       this.modifiedby = modifiedby;
       this.validatedby = validatedby;
       this.lasttimevisit = lasttimevisit;
       this.pstatus = pstatus;
       this.password = password;
    }
   
    public String getParentId() {
        return this.parentId;
    }
    
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getQualification() {
        return this.qualification;
    }
    
    public void setQualification(String qualification) {
        this.qualification = qualification;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getMobileno() {
        return this.mobileno;
    }
    
    public void setMobileno(String mobileno) {
        this.mobileno = mobileno;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Timestamp getCreatedate() {
        return this.createdate;
    }
    
    public void setCreatedate(Timestamp createdate) {
        this.createdate = createdate;
    }
    public String getModifiedby() {
        return this.modifiedby;
    }
    
    public void setModifiedby(String modifiedby) {
        this.modifiedby = modifiedby;
    }
    public String getValidatedby() {
        return this.validatedby;
    }
    
    public void setValidatedby(String validatedby) {
        this.validatedby = validatedby;
    }
    public Date getLasttimevisit() {
        return this.lasttimevisit;
    }
    
    public void setLasttimevisit(Date lasttimevisit) {
        this.lasttimevisit = lasttimevisit;
    }
    public String getPstatus() {
        return this.pstatus;
    }
    
    public void setPstatus(String pstatus) {
        this.pstatus = pstatus;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


